package com.whxx.hms.model;

import java.util.Date;

public class Building {
    /**
    *   
     */
    private String buildingId;

    /**
    *   
     */
    private Integer hotelGroupId;

    /**
    *   
     */
    private Integer hotelId;

    /**
    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
     */
    private String lineNo;

    /**
    *   代码
     */
    private String buildingCode;

    /**
    *   中文名
     */
    private String buildingName;

    /**
    *   英文名
     */
    private String buildingEnName;

    /**
    *   
     */
    private String remark;

    /**
    *   序号
     */
    private Integer seq;

    /**
    *   是否停用 Y N
     */
    private String stopped;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.BUILDING_ID_
     *
     * @return the value of building.BUILDING_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.BUILDING_ID_
     *
     * @param buildingId the value for building.BUILDING_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setBuildingId(String buildingId) {
        this.buildingId = buildingId == null ? null : buildingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.HOTEL_GROUP_ID_
     *
     * @return the value of building.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for building.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.HOTEL_ID_
     *
     * @return the value of building.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.HOTEL_ID_
     *
     * @param hotelId the value for building.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.LINE_NO_
     *
     * @return the value of building.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.LINE_NO_
     *
     * @param lineNo the value for building.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setLineNo(String lineNo) {
        this.lineNo = lineNo == null ? null : lineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.BUILDING_CODE_
     *
     * @return the value of building.BUILDING_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getBuildingCode() {
        return buildingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.BUILDING_CODE_
     *
     * @param buildingCode the value for building.BUILDING_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setBuildingCode(String buildingCode) {
        this.buildingCode = buildingCode == null ? null : buildingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.BUILDING_NAME_
     *
     * @return the value of building.BUILDING_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.BUILDING_NAME_
     *
     * @param buildingName the value for building.BUILDING_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName == null ? null : buildingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.BUILDING_EN_NAME_
     *
     * @return the value of building.BUILDING_EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getBuildingEnName() {
        return buildingEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.BUILDING_EN_NAME_
     *
     * @param buildingEnName the value for building.BUILDING_EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setBuildingEnName(String buildingEnName) {
        this.buildingEnName = buildingEnName == null ? null : buildingEnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.REMARK
     *
     * @return the value of building.REMARK
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.REMARK
     *
     * @param remark the value for building.REMARK
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.SEQ_
     *
     * @return the value of building.SEQ_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.SEQ_
     *
     * @param seq the value for building.SEQ_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.STOPPED_
     *
     * @return the value of building.STOPPED_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getStopped() {
        return stopped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.STOPPED_
     *
     * @param stopped the value for building.STOPPED_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setStopped(String stopped) {
        this.stopped = stopped == null ? null : stopped.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.CREATE_EMP_
     *
     * @return the value of building.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.CREATE_EMP_
     *
     * @param createEmp the value for building.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.CREATE_DATE_
     *
     * @return the value of building.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.CREATE_DATE_
     *
     * @param createDate the value for building.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.UPDATE_DATE_
     *
     * @return the value of building.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.UPDATE_DATE_
     *
     * @param updateDate the value for building.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.UPDATE_EMP_
     *
     * @return the value of building.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.UPDATE_EMP_
     *
     * @param updateEmp the value for building.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.VERSION
     *
     * @return the value of building.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.VERSION
     *
     * @param version the value for building.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}