package com.whxx.hms.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 消费信息
 * @ClassName: Consume 
 * @Description: TODO
 * @author: zengxin
 * @date: 2018年5月31日 上午9:34:28
 */
public class Consume {
    /**
    *   
     */
    private String consumeId;

    /**
    *   集团id
     */
    private Integer hotelGroupId;

    /**
    *   酒店id
     */
    private Integer hotelId;

    /**
    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
     */
    private String lineNo;

    /**
    *   订单号规则      YYMMDD00001开始累加，每天前缀都会变化，子订单和主订单共用同一个序列
     */
    private String priMainId;

    /**
    *   订单号规则      YYMMDD00001开始累加，每天前缀都会变化，子订单和主订单共用同一个序列
     */
    private String mainId;

    /**
    *   子订单号规则  YYMMDD00001开始累加，每天前缀都会变化
     */
    private String subId;

    /**
    *   是否预授权 Y 是，N否
     */
    private String preFlag;

    /**
    *   是否计入房费：Y是，N否
     */
    private String inRoom;

    /**
    *   入账类型  来源于配置  入账类型代码.ACCOUNT_TYPE 模板一样
     */
    private String accountType;
    
    /**
     *   入账类型  来源于配置  入账类型代码.ACCOUNT_TYPE 模板一样
      */
     private String accountTypeName;

    /**
    *   小商品类型，此类型默认的ACCOUNT_TYPE为小商品的子类. 
     */
    private String goodType;

    /**
    *   账目类型：1入账，2冲账
     */
    private String inType;

    /**
    *   第三方支付单号，支付宝微信生成
     */
    private String thirdNo;

    /**
    *   第四方支付单号，由我们生成
     */
    private String myNo;

    /**
    *   银行卡号
     */
    private String bankNo;

    /**
    *   交易单号，银行卡使用
     */
    private String payNo;

    /**
    *   付款人，使用银行卡时记录
     */
    private String payPerson;

    /**
    *   冲账原因：IN_CODE
     */
    private String inCode;
    
    /**
     * 金额
     */
     private BigDecimal gold;

    /**
    *   备注
     */
    private String remark;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;
    

    public String getAccountTypeName() {
		return accountTypeName;
	}

	public void setAccountTypeName(String accountTypeName) {
		this.accountTypeName = accountTypeName;
	}

	public BigDecimal getGold() {
		return gold;
	}

	public void setGold(BigDecimal gold) {
		this.gold = gold;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.CONSUME_ID_
     *
     * @return the value of consume.CONSUME_ID_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getConsumeId() {
        return consumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.CONSUME_ID_
     *
     * @param consumeId the value for consume.CONSUME_ID_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setConsumeId(String consumeId) {
        this.consumeId = consumeId == null ? null : consumeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.HOTEL_GROUP_ID_
     *
     * @return the value of consume.HOTEL_GROUP_ID_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for consume.HOTEL_GROUP_ID_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.HOTEL_ID_
     *
     * @return the value of consume.HOTEL_ID_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.HOTEL_ID_
     *
     * @param hotelId the value for consume.HOTEL_ID_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.LINE_NO_
     *
     * @return the value of consume.LINE_NO_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.LINE_NO_
     *
     * @param lineNo the value for consume.LINE_NO_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setLineNo(String lineNo) {
        this.lineNo = lineNo == null ? null : lineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.PRI_MAIN_ID_
     *
     * @return the value of consume.PRI_MAIN_ID_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getPriMainId() {
        return priMainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.PRI_MAIN_ID_
     *
     * @param priMainId the value for consume.PRI_MAIN_ID_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setPriMainId(String priMainId) {
        this.priMainId = priMainId == null ? null : priMainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.MAIN_ID_
     *
     * @return the value of consume.MAIN_ID_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getMainId() {
        return mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.MAIN_ID_
     *
     * @param mainId the value for consume.MAIN_ID_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setMainId(String mainId) {
        this.mainId = mainId == null ? null : mainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.SUB_ID_
     *
     * @return the value of consume.SUB_ID_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getSubId() {
        return subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.SUB_ID_
     *
     * @param subId the value for consume.SUB_ID_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setSubId(String subId) {
        this.subId = subId == null ? null : subId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.PRE_FLAG_
     *
     * @return the value of consume.PRE_FLAG_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getPreFlag() {
        return preFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.PRE_FLAG_
     *
     * @param preFlag the value for consume.PRE_FLAG_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setPreFlag(String preFlag) {
        this.preFlag = preFlag == null ? null : preFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.IN_ROOM_
     *
     * @return the value of consume.IN_ROOM_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getInRoom() {
        return inRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.IN_ROOM_
     *
     * @param inRoom the value for consume.IN_ROOM_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setInRoom(String inRoom) {
        this.inRoom = inRoom == null ? null : inRoom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.ACCOUNT_TYPE_
     *
     * @return the value of consume.ACCOUNT_TYPE_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.ACCOUNT_TYPE_
     *
     * @param accountType the value for consume.ACCOUNT_TYPE_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.GOOD_TYPE_
     *
     * @return the value of consume.GOOD_TYPE_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getGoodType() {
        return goodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.GOOD_TYPE_
     *
     * @param goodType the value for consume.GOOD_TYPE_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setGoodType(String goodType) {
        this.goodType = goodType == null ? null : goodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.IN_TYPE_
     *
     * @return the value of consume.IN_TYPE_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getInType() {
        return inType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.IN_TYPE_
     *
     * @param inType the value for consume.IN_TYPE_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setInType(String inType) {
        this.inType = inType == null ? null : inType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.THIRD_NO_
     *
     * @return the value of consume.THIRD_NO_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getThirdNo() {
        return thirdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.THIRD_NO_
     *
     * @param thirdNo the value for consume.THIRD_NO_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setThirdNo(String thirdNo) {
        this.thirdNo = thirdNo == null ? null : thirdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.MY_NO_
     *
     * @return the value of consume.MY_NO_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getMyNo() {
        return myNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.MY_NO_
     *
     * @param myNo the value for consume.MY_NO_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setMyNo(String myNo) {
        this.myNo = myNo == null ? null : myNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.BANK_NO_
     *
     * @return the value of consume.BANK_NO_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.BANK_NO_
     *
     * @param bankNo the value for consume.BANK_NO_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.PAY_NO_
     *
     * @return the value of consume.PAY_NO_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.PAY_NO_
     *
     * @param payNo the value for consume.PAY_NO_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setPayNo(String payNo) {
        this.payNo = payNo == null ? null : payNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.PAY_PERSON_
     *
     * @return the value of consume.PAY_PERSON_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getPayPerson() {
        return payPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.PAY_PERSON_
     *
     * @param payPerson the value for consume.PAY_PERSON_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setPayPerson(String payPerson) {
        this.payPerson = payPerson == null ? null : payPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.IN_CODE_
     *
     * @return the value of consume.IN_CODE_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getInCode() {
        return inCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.IN_CODE_
     *
     * @param inCode the value for consume.IN_CODE_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setInCode(String inCode) {
        this.inCode = inCode == null ? null : inCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.REMARK_
     *
     * @return the value of consume.REMARK_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.REMARK_
     *
     * @param remark the value for consume.REMARK_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.CREATE_EMP_
     *
     * @return the value of consume.CREATE_EMP_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.CREATE_EMP_
     *
     * @param createEmp the value for consume.CREATE_EMP_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.CREATE_DATE_
     *
     * @return the value of consume.CREATE_DATE_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.CREATE_DATE_
     *
     * @param createDate the value for consume.CREATE_DATE_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.UPDATE_DATE_
     *
     * @return the value of consume.UPDATE_DATE_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.UPDATE_DATE_
     *
     * @param updateDate the value for consume.UPDATE_DATE_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.UPDATE_EMP_
     *
     * @return the value of consume.UPDATE_EMP_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.UPDATE_EMP_
     *
     * @param updateEmp the value for consume.UPDATE_EMP_
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume.VERSION
     *
     * @return the value of consume.VERSION
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume.VERSION
     *
     * @param version the value for consume.VERSION
     *
     * @mbggenerated Wed May 30 18:50:32 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}