package com.whxx.hms.model;

import java.util.Date;

public class ConsumeCode {
    /**
    *   主键
     */
    private String consumeCodeId;

    /**
    *   
     */
    private Integer hotelGroupId;

    /**
    *   
     */
    private Integer hotelId;

    /**
    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
     */
    private String lineNo;

    /**
    *   序号
     */
    private Integer seq;

    /**
    *   费用代码
     */
    private String consumeCode;

    /**
    *   
     */
    private String zhName;

    /**
    *   
     */
    private String enName;

    /**
    *   使用范围
     */
    private String areas;

    /**
    *   费用类别
     */
    private String costType;

    /**
    *   营业部门
     */
    private String opDivision;

    /**
    *   记账类别
     */
    private String ioAccountType;

    /**
    *   余额表
     */
    private String balanceTable;

    /**
    *   业绩统计，代码同BALANCE_TABLE_ 余额表
     */
    private String achievementCount;

    /**
    *   是否停用 Y N
     */
    private String stopped;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.CONSUME_CODE_ID_
     *
     * @return the value of consume_code.CONSUME_CODE_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getConsumeCodeId() {
        return consumeCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.CONSUME_CODE_ID_
     *
     * @param consumeCodeId the value for consume_code.CONSUME_CODE_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setConsumeCodeId(String consumeCodeId) {
        this.consumeCodeId = consumeCodeId == null ? null : consumeCodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.HOTEL_GROUP_ID_
     *
     * @return the value of consume_code.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for consume_code.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.HOTEL_ID_
     *
     * @return the value of consume_code.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.HOTEL_ID_
     *
     * @param hotelId the value for consume_code.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.LINE_NO_
     *
     * @return the value of consume_code.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.LINE_NO_
     *
     * @param lineNo the value for consume_code.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setLineNo(String lineNo) {
        this.lineNo = lineNo == null ? null : lineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.SEQ_
     *
     * @return the value of consume_code.SEQ_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.SEQ_
     *
     * @param seq the value for consume_code.SEQ_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.CONSUME_CODE_
     *
     * @return the value of consume_code.CONSUME_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getConsumeCode() {
        return consumeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.CONSUME_CODE_
     *
     * @param consumeCode the value for consume_code.CONSUME_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setConsumeCode(String consumeCode) {
        this.consumeCode = consumeCode == null ? null : consumeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.ZH_NAME_
     *
     * @return the value of consume_code.ZH_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getZhName() {
        return zhName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.ZH_NAME_
     *
     * @param zhName the value for consume_code.ZH_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setZhName(String zhName) {
        this.zhName = zhName == null ? null : zhName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.EN_NAME_
     *
     * @return the value of consume_code.EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.EN_NAME_
     *
     * @param enName the value for consume_code.EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.AREAS_
     *
     * @return the value of consume_code.AREAS_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getAreas() {
        return areas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.AREAS_
     *
     * @param areas the value for consume_code.AREAS_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setAreas(String areas) {
        this.areas = areas == null ? null : areas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.COST_TYPE_
     *
     * @return the value of consume_code.COST_TYPE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getCostType() {
        return costType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.COST_TYPE_
     *
     * @param costType the value for consume_code.COST_TYPE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCostType(String costType) {
        this.costType = costType == null ? null : costType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.OP_DIVISION_
     *
     * @return the value of consume_code.OP_DIVISION_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getOpDivision() {
        return opDivision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.OP_DIVISION_
     *
     * @param opDivision the value for consume_code.OP_DIVISION_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setOpDivision(String opDivision) {
        this.opDivision = opDivision == null ? null : opDivision.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.IO_ACCOUNT_TYPE_
     *
     * @return the value of consume_code.IO_ACCOUNT_TYPE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getIoAccountType() {
        return ioAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.IO_ACCOUNT_TYPE_
     *
     * @param ioAccountType the value for consume_code.IO_ACCOUNT_TYPE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setIoAccountType(String ioAccountType) {
        this.ioAccountType = ioAccountType == null ? null : ioAccountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.BALANCE_TABLE_
     *
     * @return the value of consume_code.BALANCE_TABLE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getBalanceTable() {
        return balanceTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.BALANCE_TABLE_
     *
     * @param balanceTable the value for consume_code.BALANCE_TABLE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setBalanceTable(String balanceTable) {
        this.balanceTable = balanceTable == null ? null : balanceTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.ACHIEVEMENT_COUNT_
     *
     * @return the value of consume_code.ACHIEVEMENT_COUNT_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getAchievementCount() {
        return achievementCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.ACHIEVEMENT_COUNT_
     *
     * @param achievementCount the value for consume_code.ACHIEVEMENT_COUNT_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setAchievementCount(String achievementCount) {
        this.achievementCount = achievementCount == null ? null : achievementCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.STOPPED_
     *
     * @return the value of consume_code.STOPPED_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getStopped() {
        return stopped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.STOPPED_
     *
     * @param stopped the value for consume_code.STOPPED_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setStopped(String stopped) {
        this.stopped = stopped == null ? null : stopped.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.CREATE_EMP_
     *
     * @return the value of consume_code.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.CREATE_EMP_
     *
     * @param createEmp the value for consume_code.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.CREATE_DATE_
     *
     * @return the value of consume_code.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.CREATE_DATE_
     *
     * @param createDate the value for consume_code.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.UPDATE_DATE_
     *
     * @return the value of consume_code.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.UPDATE_DATE_
     *
     * @param updateDate the value for consume_code.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.UPDATE_EMP_
     *
     * @return the value of consume_code.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.UPDATE_EMP_
     *
     * @param updateEmp the value for consume_code.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_code.VERSION
     *
     * @return the value of consume_code.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_code.VERSION
     *
     * @param version the value for consume_code.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}