package com.whxx.hms.model;

import java.util.Date;

public class Floor {
    /**
    *   
     */
    private String floorId;

    /**
    *   
     */
    private Integer hotelGroupId;

    /**
    *   
     */
    private Integer hotelId;

    /**
    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
     */
    private String lineNo;

    /**
    *   
     */
    private String floorCode;

    /**
    *   楼层名
     */
    private String floorName;

    /**
    *   楼层英文名
     */
    private String floorEnName;

    /**
    *   
     */
    private String buildingEnName;

    /**
    *   
     */
    private String buildingName;

    /**
    *   
     */
    private String buildingCode;

    /**
    *   序号
     */
    private Integer seq;

    /**
    *   是否停用 Y N
     */
    private String stopped;

    /**
    *   
     */
    private String remark;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.FLOOR_ID_
     *
     * @return the value of floor.FLOOR_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getFloorId() {
        return floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.FLOOR_ID_
     *
     * @param floorId the value for floor.FLOOR_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setFloorId(String floorId) {
        this.floorId = floorId == null ? null : floorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.HOTEL_GROUP_ID_
     *
     * @return the value of floor.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for floor.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.HOTEL_ID_
     *
     * @return the value of floor.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.HOTEL_ID_
     *
     * @param hotelId the value for floor.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.LINE_NO_
     *
     * @return the value of floor.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.LINE_NO_
     *
     * @param lineNo the value for floor.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setLineNo(String lineNo) {
        this.lineNo = lineNo == null ? null : lineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.FLOOR_CODE_
     *
     * @return the value of floor.FLOOR_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getFloorCode() {
        return floorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.FLOOR_CODE_
     *
     * @param floorCode the value for floor.FLOOR_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setFloorCode(String floorCode) {
        this.floorCode = floorCode == null ? null : floorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.FLOOR_NAME_
     *
     * @return the value of floor.FLOOR_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getFloorName() {
        return floorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.FLOOR_NAME_
     *
     * @param floorName the value for floor.FLOOR_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setFloorName(String floorName) {
        this.floorName = floorName == null ? null : floorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.FLOOR_EN_NAME_
     *
     * @return the value of floor.FLOOR_EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getFloorEnName() {
        return floorEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.FLOOR_EN_NAME_
     *
     * @param floorEnName the value for floor.FLOOR_EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setFloorEnName(String floorEnName) {
        this.floorEnName = floorEnName == null ? null : floorEnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.BUILDING_EN_NAME_
     *
     * @return the value of floor.BUILDING_EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getBuildingEnName() {
        return buildingEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.BUILDING_EN_NAME_
     *
     * @param buildingEnName the value for floor.BUILDING_EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setBuildingEnName(String buildingEnName) {
        this.buildingEnName = buildingEnName == null ? null : buildingEnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.BUILDING_NAME_
     *
     * @return the value of floor.BUILDING_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.BUILDING_NAME_
     *
     * @param buildingName the value for floor.BUILDING_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName == null ? null : buildingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.BUILDING_CODE_
     *
     * @return the value of floor.BUILDING_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getBuildingCode() {
        return buildingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.BUILDING_CODE_
     *
     * @param buildingCode the value for floor.BUILDING_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setBuildingCode(String buildingCode) {
        this.buildingCode = buildingCode == null ? null : buildingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.SEQ_
     *
     * @return the value of floor.SEQ_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.SEQ_
     *
     * @param seq the value for floor.SEQ_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.STOPPED_
     *
     * @return the value of floor.STOPPED_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getStopped() {
        return stopped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.STOPPED_
     *
     * @param stopped the value for floor.STOPPED_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setStopped(String stopped) {
        this.stopped = stopped == null ? null : stopped.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.REMARK
     *
     * @return the value of floor.REMARK
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.REMARK
     *
     * @param remark the value for floor.REMARK
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.CREATE_EMP_
     *
     * @return the value of floor.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.CREATE_EMP_
     *
     * @param createEmp the value for floor.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.CREATE_DATE_
     *
     * @return the value of floor.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.CREATE_DATE_
     *
     * @param createDate the value for floor.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.UPDATE_DATE_
     *
     * @return the value of floor.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.UPDATE_DATE_
     *
     * @param updateDate the value for floor.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.UPDATE_EMP_
     *
     * @return the value of floor.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.UPDATE_EMP_
     *
     * @param updateEmp the value for floor.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.VERSION
     *
     * @return the value of floor.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.VERSION
     *
     * @param version the value for floor.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}