package com.whxx.hms.model;

import java.util.Date;

/**
 * 留言和备注
 * @ClassName: OtherInfo 
 * @Description: TODO
 * @author: zengxin
 * @date: 2018年5月30日 下午2:31:57
 */
public class Messages {
		/**
	     *   主键
	     */
	    private String messagesId;

	    /**
	    *   
	     */
	    private Integer hotelGroupId;

	    /**
	    *   
	     */
	    private Integer hotelId;

	    /**
	    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
	     */
	    private String lineNo;

	    /**
	    *   主预定号 规则 YYMMDD00001开始累加，每天前缀都会变化
	     */
	    private String mainId;

	    /**
	    *   是否已读 Y N
	     */
	    private String readFlag;

	    /**
	    *   开始时间
	     */
	    private Date startTime;

	    /**
	    *   结束时间
	     */
	    private Date endTime;
	    
	    /**
	    *   备注
	     */
	    private String remark;
	    
	    /**
		  *   房号
		  */
		private String roomCode;

	    /**
	    *   入住人
	     */
	    private String person;

	    /**
	    *   新增时间
	     */
	    private String createDate;

	    /**
	    *   新增人
	     */
	    private String createEmp;

	    /**
	    *   修改时间
	     */
	    private Date updateDate;

	    /**
	    *   修改人
	     */
	    private String updateEmp;

	    /**
	    *   版本
	     */
	    private Integer version;
	    
	    public String getRoomCode() {
			return roomCode;
		}

		public void setRoomCode(String roomCode) {
			this.roomCode = roomCode;
		}

		public String getPerson() {
			return person;
		}

		public void setPerson(String person) {
			this.person = person;
		}

		/**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column messages.MESSAGES_ID_
	     *
	     * @return the value of messages.MESSAGES_ID_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public String getMessagesId() {
	        return messagesId;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column messages.MESSAGES_ID_
	     *
	     * @param messagesId the value for messages.MESSAGES_ID_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public void setMessagesId(String messagesId) {
	        this.messagesId = messagesId == null ? null : messagesId.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column messages.HOTEL_GROUP_ID_
	     *
	     * @return the value of messages.HOTEL_GROUP_ID_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public Integer getHotelGroupId() {
	        return hotelGroupId;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column messages.HOTEL_GROUP_ID_
	     *
	     * @param hotelGroupId the value for messages.HOTEL_GROUP_ID_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public void setHotelGroupId(Integer hotelGroupId) {
	        this.hotelGroupId = hotelGroupId;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column messages.HOTEL_ID_
	     *
	     * @return the value of messages.HOTEL_ID_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public Integer getHotelId() {
	        return hotelId;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column messages.HOTEL_ID_
	     *
	     * @param hotelId the value for messages.HOTEL_ID_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public void setHotelId(Integer hotelId) {
	        this.hotelId = hotelId;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column messages.LINE_NO_
	     *
	     * @return the value of messages.LINE_NO_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public String getLineNo() {
	        return lineNo;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column messages.LINE_NO_
	     *
	     * @param lineNo the value for messages.LINE_NO_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public void setLineNo(String lineNo) {
	        this.lineNo = lineNo == null ? null : lineNo.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column messages.MAIN_ID_
	     *
	     * @return the value of messages.MAIN_ID_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public String getMainId() {
	        return mainId;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column messages.MAIN_ID_
	     *
	     * @param mainId the value for messages.MAIN_ID_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public void setMainId(String mainId) {
	        this.mainId = mainId == null ? null : mainId.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column messages.READ_FLAG_
	     *
	     * @return the value of messages.READ_FLAG_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public String getReadFlag() {
	        return readFlag;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column messages.READ_FLAG_
	     *
	     * @param readFlag the value for messages.READ_FLAG_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public void setReadFlag(String readFlag) {
	        this.readFlag = readFlag == null ? null : readFlag.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column messages.START_TIME_
	     *
	     * @return the value of messages.START_TIME_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public Date getStartTime() {
	        return startTime;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column messages.START_TIME_
	     *
	     * @param startTime the value for messages.START_TIME_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public void setStartTime(Date startTime) {
	        this.startTime = startTime;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column messages.END_TIME_
	     *
	     * @return the value of messages.END_TIME_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public Date getEndTime() {
	        return endTime;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column messages.END_TIME_
	     *
	     * @param endTime the value for messages.END_TIME_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public void setEndTime(Date endTime) {
	        this.endTime = endTime;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column messages.REMARK_
	     *
	     * @return the value of messages.REMARK_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public String getRemark() {
	        return remark;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column messages.REMARK_
	     *
	     * @param remark the value for messages.REMARK_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public void setRemark(String remark) {
	        this.remark = remark == null ? null : remark.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column messages.CREATE_DATE_
	     *
	     * @return the value of messages.CREATE_DATE_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public String getCreateDate() {
	        return createDate;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column messages.CREATE_DATE_
	     *
	     * @param createDate the value for messages.CREATE_DATE_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public void setCreateDate(String createDate) {
	        this.createDate = createDate;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column messages.CREATE_EMP_
	     *
	     * @return the value of messages.CREATE_EMP_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public String getCreateEmp() {
	        return createEmp;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column messages.CREATE_EMP_
	     *
	     * @param createEmp the value for messages.CREATE_EMP_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public void setCreateEmp(String createEmp) {
	        this.createEmp = createEmp == null ? null : createEmp.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column messages.UPDATE_DATE_
	     *
	     * @return the value of messages.UPDATE_DATE_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public Date getUpdateDate() {
	        return updateDate;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column messages.UPDATE_DATE_
	     *
	     * @param updateDate the value for messages.UPDATE_DATE_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public void setUpdateDate(Date updateDate) {
	        this.updateDate = updateDate;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column messages.UPDATE_EMP_
	     *
	     * @return the value of messages.UPDATE_EMP_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public String getUpdateEmp() {
	        return updateEmp;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column messages.UPDATE_EMP_
	     *
	     * @param updateEmp the value for messages.UPDATE_EMP_
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public void setUpdateEmp(String updateEmp) {
	        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column messages.VERSION
	     *
	     * @return the value of messages.VERSION
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public Integer getVersion() {
	        return version;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column messages.VERSION
	     *
	     * @param version the value for messages.VERSION
	     *
	     * @mbggenerated Wed May 30 14:31:11 CST 2018
	     */
	    public void setVersion(Integer version) {
	        this.version = version;
	    }
}
