package com.whxx.hms.model;

import java.util.Date;

public class ModifyLogs {
    /**
    *   主键
     */
    private String modifyLogsId;

    /**
    *   集团ID
     */
    private Integer hotelGroupId;

    /**
    *   酒店ID
     */
    private Integer hotelId;

    /**
    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
     */
    private String lineNo;

    /**
    *   表名
     */
    private String tableName;

    /**
    *   项目值(表中具体字段)
     */
    private String project;

    /**
    *   老状态
     */
    private String oldInfo;

    /**
    *   新状态
     */
    private String newInfo;
    
    /**
     *   预订单号
      */
     private String priMainId;

    /**
    *   表名
     */
    private String remark1;

    /**
    *   项目值(表中具体字段)
     */
    private String remark2;

    /**
    *   老状态
     */
    private String remark3;

    /**
    *   新状态
     */
    private String remark4;
    
    /**
     *   完整的记录修改信息
      */
     private String info;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private String createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;
    

    public String getPriMainId() {
		return priMainId;
	}

	public void setPriMainId(String priMainId) {
		this.priMainId = priMainId;
	}

	public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.MODIFY_LOGS_ID_
     *
     * @return the value of modify_logs.MODIFY_LOGS_ID_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public String getModifyLogsId() {
        return modifyLogsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.MODIFY_LOGS_ID_
     *
     * @param modifyLogsId the value for modify_logs.MODIFY_LOGS_ID_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setModifyLogsId(String modifyLogsId) {
        this.modifyLogsId = modifyLogsId == null ? null : modifyLogsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.HOTEL_GROUP_ID_
     *
     * @return the value of modify_logs.HOTEL_GROUP_ID_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for modify_logs.HOTEL_GROUP_ID_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.HOTEL_ID_
     *
     * @return the value of modify_logs.HOTEL_ID_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.HOTEL_ID_
     *
     * @param hotelId the value for modify_logs.HOTEL_ID_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.LINE_NO_
     *
     * @return the value of modify_logs.LINE_NO_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public String getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.LINE_NO_
     *
     * @param lineNo the value for modify_logs.LINE_NO_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setLineNo(String lineNo) {
        this.lineNo = lineNo == null ? null : lineNo.trim();
    }

    public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.PROJECT_
     *
     * @return the value of modify_logs.PROJECT_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.PROJECT_
     *
     * @param project the value for modify_logs.PROJECT_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.OLD_INFO_
     *
     * @return the value of modify_logs.OLD_INFO_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public String getOldInfo() {
        return oldInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.OLD_INFO_
     *
     * @param oldInfo the value for modify_logs.OLD_INFO_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setOldInfo(String oldInfo) {
        this.oldInfo = oldInfo == null ? null : oldInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.NEW_INFO_
     *
     * @return the value of modify_logs.NEW_INFO_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public String getNewInfo() {
        return newInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.NEW_INFO_
     *
     * @param newInfo the value for modify_logs.NEW_INFO_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setNewInfo(String newInfo) {
        this.newInfo = newInfo == null ? null : newInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.REMARK1_
     *
     * @return the value of modify_logs.REMARK1_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.REMARK1_
     *
     * @param remark1 the value for modify_logs.REMARK1_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.REMARK2_
     *
     * @return the value of modify_logs.REMARK2_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.REMARK2_
     *
     * @param remark2 the value for modify_logs.REMARK2_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.REMARK3_
     *
     * @return the value of modify_logs.REMARK3_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.REMARK3_
     *
     * @param remark3 the value for modify_logs.REMARK3_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.REMARK4_
     *
     * @return the value of modify_logs.REMARK4_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public String getRemark4() {
        return remark4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.REMARK4_
     *
     * @param remark4 the value for modify_logs.REMARK4_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setRemark4(String remark4) {
        this.remark4 = remark4 == null ? null : remark4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.CREATE_EMP_
     *
     * @return the value of modify_logs.CREATE_EMP_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.CREATE_EMP_
     *
     * @param createEmp the value for modify_logs.CREATE_EMP_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.CREATE_DATE_
     *
     * @return the value of modify_logs.CREATE_DATE_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.CREATE_DATE_
     *
     * @param createDate the value for modify_logs.CREATE_DATE_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.UPDATE_DATE_
     *
     * @return the value of modify_logs.UPDATE_DATE_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.UPDATE_DATE_
     *
     * @param updateDate the value for modify_logs.UPDATE_DATE_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.UPDATE_EMP_
     *
     * @return the value of modify_logs.UPDATE_EMP_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.UPDATE_EMP_
     *
     * @param updateEmp the value for modify_logs.UPDATE_EMP_
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_logs.VERSION
     *
     * @return the value of modify_logs.VERSION
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_logs.VERSION
     *
     * @param version the value for modify_logs.VERSION
     *
     * @mbggenerated Mon Jun 18 11:50:25 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}