package com.whxx.hms.model;

import java.util.Date;

public class PayCode {
    /**
    *   
     */
    private String payCodeId;

    /**
    *   
     */
    private Integer hotelGroupId;

    /**
    *   
     */
    private Integer hotelId;

    /**
    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
     */
    private String lineNo;

    /**
    *   序号
     */
    private Integer seq;

    /**
    *   费用代码
     */
    private String payCode;

    /**
    *   
     */
    private String zhName;

    /**
    *   
     */
    private String enName;

    /**
    *   使用范围
     */
    private String areas;

    /**
    *   付款类别
     */
    private String payType;

    /**
    *   内部码
     */
    private String innerCode;

    /**
    *   退款码
     */
    private String backpayCode;

    /**
    *   是否信用卡 Y N
     */
    private String creditFlag;

    /**
    *   只能做结账使用，不能做定金  Y N 
     */
    private String earnestFlag;

    /**
    *   是否停用 Y N
     */
    private String stopped;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.PAY_CODE_ID_
     *
     * @return the value of pay_code.PAY_CODE_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getPayCodeId() {
        return payCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.PAY_CODE_ID_
     *
     * @param payCodeId the value for pay_code.PAY_CODE_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setPayCodeId(String payCodeId) {
        this.payCodeId = payCodeId == null ? null : payCodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.HOTEL_GROUP_ID_
     *
     * @return the value of pay_code.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for pay_code.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.HOTEL_ID_
     *
     * @return the value of pay_code.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.HOTEL_ID_
     *
     * @param hotelId the value for pay_code.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.LINE_NO_
     *
     * @return the value of pay_code.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.LINE_NO_
     *
     * @param lineNo the value for pay_code.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setLineNo(String lineNo) {
        this.lineNo = lineNo == null ? null : lineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.SEQ_
     *
     * @return the value of pay_code.SEQ_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.SEQ_
     *
     * @param seq the value for pay_code.SEQ_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.PAY_CODE_
     *
     * @return the value of pay_code.PAY_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getPayCode() {
        return payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.PAY_CODE_
     *
     * @param payCode the value for pay_code.PAY_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setPayCode(String payCode) {
        this.payCode = payCode == null ? null : payCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.ZH_NAME_
     *
     * @return the value of pay_code.ZH_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getZhName() {
        return zhName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.ZH_NAME_
     *
     * @param zhName the value for pay_code.ZH_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setZhName(String zhName) {
        this.zhName = zhName == null ? null : zhName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.EN_NAME_
     *
     * @return the value of pay_code.EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.EN_NAME_
     *
     * @param enName the value for pay_code.EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.AREAS_
     *
     * @return the value of pay_code.AREAS_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getAreas() {
        return areas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.AREAS_
     *
     * @param areas the value for pay_code.AREAS_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setAreas(String areas) {
        this.areas = areas == null ? null : areas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.PAY_TYPE_
     *
     * @return the value of pay_code.PAY_TYPE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.PAY_TYPE_
     *
     * @param payType the value for pay_code.PAY_TYPE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.INNER_CODE_
     *
     * @return the value of pay_code.INNER_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getInnerCode() {
        return innerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.INNER_CODE_
     *
     * @param innerCode the value for pay_code.INNER_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setInnerCode(String innerCode) {
        this.innerCode = innerCode == null ? null : innerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.BACKPAY_CODE_
     *
     * @return the value of pay_code.BACKPAY_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getBackpayCode() {
        return backpayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.BACKPAY_CODE_
     *
     * @param backpayCode the value for pay_code.BACKPAY_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setBackpayCode(String backpayCode) {
        this.backpayCode = backpayCode == null ? null : backpayCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.CREDIT_FLAG_
     *
     * @return the value of pay_code.CREDIT_FLAG_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getCreditFlag() {
        return creditFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.CREDIT_FLAG_
     *
     * @param creditFlag the value for pay_code.CREDIT_FLAG_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreditFlag(String creditFlag) {
        this.creditFlag = creditFlag == null ? null : creditFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.EARNEST_FLAG_
     *
     * @return the value of pay_code.EARNEST_FLAG_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getEarnestFlag() {
        return earnestFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.EARNEST_FLAG_
     *
     * @param earnestFlag the value for pay_code.EARNEST_FLAG_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setEarnestFlag(String earnestFlag) {
        this.earnestFlag = earnestFlag == null ? null : earnestFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.STOPPED_
     *
     * @return the value of pay_code.STOPPED_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getStopped() {
        return stopped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.STOPPED_
     *
     * @param stopped the value for pay_code.STOPPED_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setStopped(String stopped) {
        this.stopped = stopped == null ? null : stopped.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.CREATE_EMP_
     *
     * @return the value of pay_code.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.CREATE_EMP_
     *
     * @param createEmp the value for pay_code.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.CREATE_DATE_
     *
     * @return the value of pay_code.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.CREATE_DATE_
     *
     * @param createDate the value for pay_code.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.UPDATE_DATE_
     *
     * @return the value of pay_code.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.UPDATE_DATE_
     *
     * @param updateDate the value for pay_code.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.UPDATE_EMP_
     *
     * @return the value of pay_code.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.UPDATE_EMP_
     *
     * @param updateEmp the value for pay_code.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_code.VERSION
     *
     * @return the value of pay_code.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_code.VERSION
     *
     * @param version the value for pay_code.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}