package com.whxx.hms.model;

import java.math.BigDecimal;
import java.util.Date;

public class PriceCodeRes {
    /**
    *   
     */
    private String priceCodeResId;

    /**
    *   
     */
    private Integer hotelGroupId;

    /**
    *   
     */
    private Integer hotelId;

    /**
    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
     */
    private String lineNo;

    /**
    *   房价码
     */
    private String priceCode;

    /**
    *   房价码名称
     */
    private String priceName;

    /**
    *   房价码类型 来自通用代码档 PRICE_TYPE 钟点房，长包房，协议房等等
     */
    private String priceType;

    /**
    *   房型码 系统配置 ROOM_TYPE_CODE
     */
    private String roomTypeCode;

    /**
    *   房型名称
     */
    private String roomTypeName;

    /**
    *   房型英文名称
     */
    private String roomTypeEnName;

    /**
    *   房间日期，房间状态所属日期 YYMMDD
     */
    private String roomDateStr;

    /**
    *   金额
     */
    private BigDecimal gold;

    /**
    *   
     */
    private String remark;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.PRICE_CODE_RES_ID_
     *
     * @return the value of price_code_res.PRICE_CODE_RES_ID_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public String getPriceCodeResId() {
        return priceCodeResId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.PRICE_CODE_RES_ID_
     *
     * @param priceCodeResId the value for price_code_res.PRICE_CODE_RES_ID_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setPriceCodeResId(String priceCodeResId) {
        this.priceCodeResId = priceCodeResId == null ? null : priceCodeResId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.HOTEL_GROUP_ID_
     *
     * @return the value of price_code_res.HOTEL_GROUP_ID_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for price_code_res.HOTEL_GROUP_ID_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.HOTEL_ID_
     *
     * @return the value of price_code_res.HOTEL_ID_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.HOTEL_ID_
     *
     * @param hotelId the value for price_code_res.HOTEL_ID_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.LINE_NO_
     *
     * @return the value of price_code_res.LINE_NO_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public String getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.LINE_NO_
     *
     * @param lineNo the value for price_code_res.LINE_NO_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setLineNo(String lineNo) {
        this.lineNo = lineNo == null ? null : lineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.PRICE_CODE_
     *
     * @return the value of price_code_res.PRICE_CODE_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public String getPriceCode() {
        return priceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.PRICE_CODE_
     *
     * @param priceCode the value for price_code_res.PRICE_CODE_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setPriceCode(String priceCode) {
        this.priceCode = priceCode == null ? null : priceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.PRICE_NAME_
     *
     * @return the value of price_code_res.PRICE_NAME_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public String getPriceName() {
        return priceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.PRICE_NAME_
     *
     * @param priceName the value for price_code_res.PRICE_NAME_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setPriceName(String priceName) {
        this.priceName = priceName == null ? null : priceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.PRICE_TYPE_
     *
     * @return the value of price_code_res.PRICE_TYPE_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public String getPriceType() {
        return priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.PRICE_TYPE_
     *
     * @param priceType the value for price_code_res.PRICE_TYPE_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setPriceType(String priceType) {
        this.priceType = priceType == null ? null : priceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.ROOM_TYPE_CODE_
     *
     * @return the value of price_code_res.ROOM_TYPE_CODE_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public String getRoomTypeCode() {
        return roomTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.ROOM_TYPE_CODE_
     *
     * @param roomTypeCode the value for price_code_res.ROOM_TYPE_CODE_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setRoomTypeCode(String roomTypeCode) {
        this.roomTypeCode = roomTypeCode == null ? null : roomTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.ROOM_TYPE_NAME_
     *
     * @return the value of price_code_res.ROOM_TYPE_NAME_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public String getRoomTypeName() {
        return roomTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.ROOM_TYPE_NAME_
     *
     * @param roomTypeName the value for price_code_res.ROOM_TYPE_NAME_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setRoomTypeName(String roomTypeName) {
        this.roomTypeName = roomTypeName == null ? null : roomTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.ROOM_TYPE_EN_NAME_
     *
     * @return the value of price_code_res.ROOM_TYPE_EN_NAME_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public String getRoomTypeEnName() {
        return roomTypeEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.ROOM_TYPE_EN_NAME_
     *
     * @param roomTypeEnName the value for price_code_res.ROOM_TYPE_EN_NAME_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setRoomTypeEnName(String roomTypeEnName) {
        this.roomTypeEnName = roomTypeEnName == null ? null : roomTypeEnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.ROOM_DATE_STR_
     *
     * @return the value of price_code_res.ROOM_DATE_STR_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public String getRoomDateStr() {
        return roomDateStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.ROOM_DATE_STR_
     *
     * @param roomDateStr the value for price_code_res.ROOM_DATE_STR_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setRoomDateStr(String roomDateStr) {
        this.roomDateStr = roomDateStr == null ? null : roomDateStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.GOLD_
     *
     * @return the value of price_code_res.GOLD_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public BigDecimal getGold() {
        return gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.GOLD_
     *
     * @param gold the value for price_code_res.GOLD_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setGold(BigDecimal gold) {
        this.gold = gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.REMARK
     *
     * @return the value of price_code_res.REMARK
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.REMARK
     *
     * @param remark the value for price_code_res.REMARK
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.CREATE_EMP_
     *
     * @return the value of price_code_res.CREATE_EMP_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.CREATE_EMP_
     *
     * @param createEmp the value for price_code_res.CREATE_EMP_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.CREATE_DATE_
     *
     * @return the value of price_code_res.CREATE_DATE_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.CREATE_DATE_
     *
     * @param createDate the value for price_code_res.CREATE_DATE_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.UPDATE_DATE_
     *
     * @return the value of price_code_res.UPDATE_DATE_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.UPDATE_DATE_
     *
     * @param updateDate the value for price_code_res.UPDATE_DATE_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.UPDATE_EMP_
     *
     * @return the value of price_code_res.UPDATE_EMP_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.UPDATE_EMP_
     *
     * @param updateEmp the value for price_code_res.UPDATE_EMP_
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code_res.VERSION
     *
     * @return the value of price_code_res.VERSION
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code_res.VERSION
     *
     * @param version the value for price_code_res.VERSION
     *
     * @mbggenerated Wed Jun 13 19:31:35 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}