package com.whxx.hms.model;

import java.util.Date;

public class PriceCode {
    /**
    *   
     */
    private String priceCodeId;

    /**
    *   
     */
    private Integer hotelGroupId;

    /**
    *   
     */
    private Integer hotelId;

    /**
    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
     */
    private String lineNo;

    /**
    *   房价码
     */
    private String priceCode;

    /**
    *   房价码名称
     */
    private String priceName;

    /**
    *   房价码类型 来自通用代码档 PRICE_TYPE 钟点房，长包房，协议房等等
     */
    private String priceType;

    /**
    *   生效开始时间
     */
    private Date startTime;

    /**
    *   生效结束时间
     */
    private Date endTime;

    /**
    *   是否停用 Y N
     */
    private String stopped;

    /**
    *   
     */
    private String remark;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.PRICE_CODE_ID_
     *
     * @return the value of price_code.PRICE_CODE_ID_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public String getPriceCodeId() {
        return priceCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.PRICE_CODE_ID_
     *
     * @param priceCodeId the value for price_code.PRICE_CODE_ID_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setPriceCodeId(String priceCodeId) {
        this.priceCodeId = priceCodeId == null ? null : priceCodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.HOTEL_GROUP_ID_
     *
     * @return the value of price_code.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for price_code.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.HOTEL_ID_
     *
     * @return the value of price_code.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.HOTEL_ID_
     *
     * @param hotelId the value for price_code.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.LINE_NO_
     *
     * @return the value of price_code.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public String getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.LINE_NO_
     *
     * @param lineNo the value for price_code.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setLineNo(String lineNo) {
        this.lineNo = lineNo == null ? null : lineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.PRICE_CODE_
     *
     * @return the value of price_code.PRICE_CODE_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public String getPriceCode() {
        return priceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.PRICE_CODE_
     *
     * @param priceCode the value for price_code.PRICE_CODE_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setPriceCode(String priceCode) {
        this.priceCode = priceCode == null ? null : priceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.PRICE_NAME_
     *
     * @return the value of price_code.PRICE_NAME_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public String getPriceName() {
        return priceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.PRICE_NAME_
     *
     * @param priceName the value for price_code.PRICE_NAME_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setPriceName(String priceName) {
        this.priceName = priceName == null ? null : priceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.PRICE_TYPE_
     *
     * @return the value of price_code.PRICE_TYPE_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public String getPriceType() {
        return priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.PRICE_TYPE_
     *
     * @param priceType the value for price_code.PRICE_TYPE_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setPriceType(String priceType) {
        this.priceType = priceType == null ? null : priceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.START_TIME_
     *
     * @return the value of price_code.START_TIME_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.START_TIME_
     *
     * @param startTime the value for price_code.START_TIME_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.END_TIME_
     *
     * @return the value of price_code.END_TIME_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.END_TIME_
     *
     * @param endTime the value for price_code.END_TIME_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.STOPPED_
     *
     * @return the value of price_code.STOPPED_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public String getStopped() {
        return stopped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.STOPPED_
     *
     * @param stopped the value for price_code.STOPPED_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setStopped(String stopped) {
        this.stopped = stopped == null ? null : stopped.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.REMARK
     *
     * @return the value of price_code.REMARK
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.REMARK
     *
     * @param remark the value for price_code.REMARK
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.CREATE_EMP_
     *
     * @return the value of price_code.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.CREATE_EMP_
     *
     * @param createEmp the value for price_code.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.CREATE_DATE_
     *
     * @return the value of price_code.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.CREATE_DATE_
     *
     * @param createDate the value for price_code.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.UPDATE_DATE_
     *
     * @return the value of price_code.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.UPDATE_DATE_
     *
     * @param updateDate the value for price_code.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.UPDATE_EMP_
     *
     * @return the value of price_code.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.UPDATE_EMP_
     *
     * @param updateEmp the value for price_code.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_code.VERSION
     *
     * @return the value of price_code.VERSION
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_code.VERSION
     *
     * @param version the value for price_code.VERSION
     *
     * @mbggenerated Thu Jun 07 19:07:33 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}