package com.whxx.hms.model;

import java.util.Date;

public class RoomTypeHistory {
    /**
    *   
     */
    private String roomTypeHistoryId;

    /**
    *   
     */
    private Integer hotelGroupId;

    /**
    *   
     */
    private Integer hotelId;

    /**
    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
     */
    private String lineNo;

    /**
    *   房型码 系统配置 ROOM_TYPE_CODE
     */
    private String roomTypeCode;

    /**
    *   房型名称
     */
    private String roomTypeName;

    /**
    *   房型英文名称
     */
    private String roomTypeEnName;

    /**
    *   房型数量
     */
    private Integer num;

    /**
    *   老超预留数量
     */
    private Integer overNumOld;

    /**
    *   新超预留数量
     */
    private Integer overNumNew;

    /**
    *   最大可住人数
     */
    private Integer maxPerson;

    /**
    *   顺序号
     */
    private Integer seq;

    /**
    *   是否停用 Y N
     */
    private String stopped;

    /**
    *   
     */
    private String remark;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.ROOM_TYPE_HISTORY_ID_
     *
     * @return the value of room_type_history.ROOM_TYPE_HISTORY_ID_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public String getRoomTypeHistoryId() {
        return roomTypeHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.ROOM_TYPE_HISTORY_ID_
     *
     * @param roomTypeHistoryId the value for room_type_history.ROOM_TYPE_HISTORY_ID_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setRoomTypeHistoryId(String roomTypeHistoryId) {
        this.roomTypeHistoryId = roomTypeHistoryId == null ? null : roomTypeHistoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.HOTEL_GROUP_ID_
     *
     * @return the value of room_type_history.HOTEL_GROUP_ID_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for room_type_history.HOTEL_GROUP_ID_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.HOTEL_ID_
     *
     * @return the value of room_type_history.HOTEL_ID_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.HOTEL_ID_
     *
     * @param hotelId the value for room_type_history.HOTEL_ID_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.LINE_NO_
     *
     * @return the value of room_type_history.LINE_NO_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public String getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.LINE_NO_
     *
     * @param lineNo the value for room_type_history.LINE_NO_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setLineNo(String lineNo) {
        this.lineNo = lineNo == null ? null : lineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.ROOM_TYPE_CODE_
     *
     * @return the value of room_type_history.ROOM_TYPE_CODE_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public String getRoomTypeCode() {
        return roomTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.ROOM_TYPE_CODE_
     *
     * @param roomTypeCode the value for room_type_history.ROOM_TYPE_CODE_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setRoomTypeCode(String roomTypeCode) {
        this.roomTypeCode = roomTypeCode == null ? null : roomTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.ROOM_TYPE_NAME_
     *
     * @return the value of room_type_history.ROOM_TYPE_NAME_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public String getRoomTypeName() {
        return roomTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.ROOM_TYPE_NAME_
     *
     * @param roomTypeName the value for room_type_history.ROOM_TYPE_NAME_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setRoomTypeName(String roomTypeName) {
        this.roomTypeName = roomTypeName == null ? null : roomTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.ROOM_TYPE_EN_NAME_
     *
     * @return the value of room_type_history.ROOM_TYPE_EN_NAME_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public String getRoomTypeEnName() {
        return roomTypeEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.ROOM_TYPE_EN_NAME_
     *
     * @param roomTypeEnName the value for room_type_history.ROOM_TYPE_EN_NAME_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setRoomTypeEnName(String roomTypeEnName) {
        this.roomTypeEnName = roomTypeEnName == null ? null : roomTypeEnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.NUM_
     *
     * @return the value of room_type_history.NUM_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.NUM_
     *
     * @param num the value for room_type_history.NUM_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.OVER_NUM_OLD_
     *
     * @return the value of room_type_history.OVER_NUM_OLD_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public Integer getOverNumOld() {
        return overNumOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.OVER_NUM_OLD_
     *
     * @param overNumOld the value for room_type_history.OVER_NUM_OLD_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setOverNumOld(Integer overNumOld) {
        this.overNumOld = overNumOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.OVER_NUM_NEW_
     *
     * @return the value of room_type_history.OVER_NUM_NEW_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public Integer getOverNumNew() {
        return overNumNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.OVER_NUM_NEW_
     *
     * @param overNumNew the value for room_type_history.OVER_NUM_NEW_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setOverNumNew(Integer overNumNew) {
        this.overNumNew = overNumNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.MAX_PERSON_
     *
     * @return the value of room_type_history.MAX_PERSON_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public Integer getMaxPerson() {
        return maxPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.MAX_PERSON_
     *
     * @param maxPerson the value for room_type_history.MAX_PERSON_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setMaxPerson(Integer maxPerson) {
        this.maxPerson = maxPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.SEQ_
     *
     * @return the value of room_type_history.SEQ_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.SEQ_
     *
     * @param seq the value for room_type_history.SEQ_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.STOPPED_
     *
     * @return the value of room_type_history.STOPPED_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public String getStopped() {
        return stopped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.STOPPED_
     *
     * @param stopped the value for room_type_history.STOPPED_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setStopped(String stopped) {
        this.stopped = stopped == null ? null : stopped.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.REMARK
     *
     * @return the value of room_type_history.REMARK
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.REMARK
     *
     * @param remark the value for room_type_history.REMARK
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.CREATE_EMP_
     *
     * @return the value of room_type_history.CREATE_EMP_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.CREATE_EMP_
     *
     * @param createEmp the value for room_type_history.CREATE_EMP_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.CREATE_DATE_
     *
     * @return the value of room_type_history.CREATE_DATE_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.CREATE_DATE_
     *
     * @param createDate the value for room_type_history.CREATE_DATE_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.UPDATE_DATE_
     *
     * @return the value of room_type_history.UPDATE_DATE_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.UPDATE_DATE_
     *
     * @param updateDate the value for room_type_history.UPDATE_DATE_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.UPDATE_EMP_
     *
     * @return the value of room_type_history.UPDATE_EMP_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.UPDATE_EMP_
     *
     * @param updateEmp the value for room_type_history.UPDATE_EMP_
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type_history.VERSION
     *
     * @return the value of room_type_history.VERSION
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type_history.VERSION
     *
     * @param version the value for room_type_history.VERSION
     *
     * @mbggenerated Fri Jun 08 09:44:14 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}