package com.whxx.hms.model;

import java.util.Date;

public class Room {
    /**
    *   主键
     */
    private String roomId;

    /**
    *   
     */
    private Integer hotelGroupId;

    /**
    *   
     */
    private Integer hotelId;

    /**
    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
     */
    private String lineNo;

    /**
    *   房间号
     */
    private String roomCode;

    /**
    *   房间名称
     */
    private String roomName;

    /**
    *   房间英文名
     */
    private String roomEnName;

    /**
    *   房型码 系统配置 ROOM_TYPE_CODE
     */
    private String roomTypeCode;

    /**
    *   房型名称
     */
    private String roomTypeName;

    /**
    *   房型英文名称
     */
    private String roomTypeEnName;

    /**
    *   门锁系统房间号
     */
    private String lockRoomNo;

    /**
    *   
     */
    private String floorCode;

    /**
    *   
     */
    private String floorName;

    /**
    *   楼层英文名
     */
    private String floorEnName;

    /**
    *   
     */
    private String buildingCode;

    /**
    *   建筑名称
     */
    private String buildingName;

    /**
    *   英文名
     */
    private String buildingEnName;

    /**
    *   序号
     */
    private Integer seq;

    /**
    *   是否停用 Y N
     */
    private String stopped;

    /**
    *   是否可用于钟点房 Y 是，N否
     */
    private String hourFlag;

    /**
    *   客房特征 ，逗号分隔的特征代码
     */
    private String roomSpec;

    /**
    *   床数
     */
    private Integer beds;

    /**
    *   电话长号
     */
    private String tel;

    /**
    *   电话短号
     */
    private String telShort;

    /**
    *   
     */
    private String remark;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.ROOM_ID
     *
     * @return the value of room.ROOM_ID
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.ROOM_ID
     *
     * @param roomId the value for room.ROOM_ID
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setRoomId(String roomId) {
        this.roomId = roomId == null ? null : roomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.HOTEL_GROUP_ID_
     *
     * @return the value of room.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for room.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.HOTEL_ID_
     *
     * @return the value of room.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.HOTEL_ID_
     *
     * @param hotelId the value for room.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.LINE_NO_
     *
     * @return the value of room.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.LINE_NO_
     *
     * @param lineNo the value for room.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setLineNo(String lineNo) {
        this.lineNo = lineNo == null ? null : lineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.ROOM_CODE_
     *
     * @return the value of room.ROOM_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getRoomCode() {
        return roomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.ROOM_CODE_
     *
     * @param roomCode the value for room.ROOM_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setRoomCode(String roomCode) {
        this.roomCode = roomCode == null ? null : roomCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.ROOM_NAME_
     *
     * @return the value of room.ROOM_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.ROOM_NAME_
     *
     * @param roomName the value for room.ROOM_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName == null ? null : roomName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.ROOM_EN_NAME_
     *
     * @return the value of room.ROOM_EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getRoomEnName() {
        return roomEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.ROOM_EN_NAME_
     *
     * @param roomEnName the value for room.ROOM_EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setRoomEnName(String roomEnName) {
        this.roomEnName = roomEnName == null ? null : roomEnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.ROOM_TYPE_CODE_
     *
     * @return the value of room.ROOM_TYPE_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getRoomTypeCode() {
        return roomTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.ROOM_TYPE_CODE_
     *
     * @param roomTypeCode the value for room.ROOM_TYPE_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setRoomTypeCode(String roomTypeCode) {
        this.roomTypeCode = roomTypeCode == null ? null : roomTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.ROOM_TYPE_NAME_
     *
     * @return the value of room.ROOM_TYPE_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getRoomTypeName() {
        return roomTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.ROOM_TYPE_NAME_
     *
     * @param roomTypeName the value for room.ROOM_TYPE_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setRoomTypeName(String roomTypeName) {
        this.roomTypeName = roomTypeName == null ? null : roomTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.ROOM_TYPE_EN_NAME_
     *
     * @return the value of room.ROOM_TYPE_EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getRoomTypeEnName() {
        return roomTypeEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.ROOM_TYPE_EN_NAME_
     *
     * @param roomTypeEnName the value for room.ROOM_TYPE_EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setRoomTypeEnName(String roomTypeEnName) {
        this.roomTypeEnName = roomTypeEnName == null ? null : roomTypeEnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.LOCK_ROOM_NO_
     *
     * @return the value of room.LOCK_ROOM_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getLockRoomNo() {
        return lockRoomNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.LOCK_ROOM_NO_
     *
     * @param lockRoomNo the value for room.LOCK_ROOM_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setLockRoomNo(String lockRoomNo) {
        this.lockRoomNo = lockRoomNo == null ? null : lockRoomNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.FLOOR_CODE_
     *
     * @return the value of room.FLOOR_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getFloorCode() {
        return floorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.FLOOR_CODE_
     *
     * @param floorCode the value for room.FLOOR_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setFloorCode(String floorCode) {
        this.floorCode = floorCode == null ? null : floorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.FLOOR_NAME_
     *
     * @return the value of room.FLOOR_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getFloorName() {
        return floorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.FLOOR_NAME_
     *
     * @param floorName the value for room.FLOOR_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setFloorName(String floorName) {
        this.floorName = floorName == null ? null : floorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.FLOOR_EN_NAME_
     *
     * @return the value of room.FLOOR_EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getFloorEnName() {
        return floorEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.FLOOR_EN_NAME_
     *
     * @param floorEnName the value for room.FLOOR_EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setFloorEnName(String floorEnName) {
        this.floorEnName = floorEnName == null ? null : floorEnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.BUILDING_CODE_
     *
     * @return the value of room.BUILDING_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getBuildingCode() {
        return buildingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.BUILDING_CODE_
     *
     * @param buildingCode the value for room.BUILDING_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setBuildingCode(String buildingCode) {
        this.buildingCode = buildingCode == null ? null : buildingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.BUILDING_NAME_
     *
     * @return the value of room.BUILDING_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.BUILDING_NAME_
     *
     * @param buildingName the value for room.BUILDING_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName == null ? null : buildingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.BUILDING_EN_NAME_
     *
     * @return the value of room.BUILDING_EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getBuildingEnName() {
        return buildingEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.BUILDING_EN_NAME_
     *
     * @param buildingEnName the value for room.BUILDING_EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setBuildingEnName(String buildingEnName) {
        this.buildingEnName = buildingEnName == null ? null : buildingEnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.SEQ_
     *
     * @return the value of room.SEQ_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.SEQ_
     *
     * @param seq the value for room.SEQ_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.STOPPED_
     *
     * @return the value of room.STOPPED_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getStopped() {
        return stopped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.STOPPED_
     *
     * @param stopped the value for room.STOPPED_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setStopped(String stopped) {
        this.stopped = stopped == null ? null : stopped.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.HOUR_FLAG_
     *
     * @return the value of room.HOUR_FLAG_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getHourFlag() {
        return hourFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.HOUR_FLAG_
     *
     * @param hourFlag the value for room.HOUR_FLAG_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHourFlag(String hourFlag) {
        this.hourFlag = hourFlag == null ? null : hourFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.ROOM_SPEC_
     *
     * @return the value of room.ROOM_SPEC_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getRoomSpec() {
        return roomSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.ROOM_SPEC_
     *
     * @param roomSpec the value for room.ROOM_SPEC_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setRoomSpec(String roomSpec) {
        this.roomSpec = roomSpec == null ? null : roomSpec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.BEDS_
     *
     * @return the value of room.BEDS_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getBeds() {
        return beds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.BEDS_
     *
     * @param beds the value for room.BEDS_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setBeds(Integer beds) {
        this.beds = beds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.TEL_
     *
     * @return the value of room.TEL_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.TEL_
     *
     * @param tel the value for room.TEL_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.TEL_SHORT_
     *
     * @return the value of room.TEL_SHORT_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getTelShort() {
        return telShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.TEL_SHORT_
     *
     * @param telShort the value for room.TEL_SHORT_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setTelShort(String telShort) {
        this.telShort = telShort == null ? null : telShort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.REMARK
     *
     * @return the value of room.REMARK
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.REMARK
     *
     * @param remark the value for room.REMARK
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.CREATE_EMP_
     *
     * @return the value of room.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.CREATE_EMP_
     *
     * @param createEmp the value for room.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.CREATE_DATE_
     *
     * @return the value of room.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.CREATE_DATE_
     *
     * @param createDate the value for room.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.UPDATE_DATE_
     *
     * @return the value of room.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.UPDATE_DATE_
     *
     * @param updateDate the value for room.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.UPDATE_EMP_
     *
     * @return the value of room.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.UPDATE_EMP_
     *
     * @param updateEmp the value for room.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.VERSION
     *
     * @return the value of room.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.VERSION
     *
     * @param version the value for room.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}