package com.whxx.hms.model;

import java.util.Date;

public class RoomPerson {
    /**
    *   
     */
    private String roomPersonId;

    /**
    *   
     */
    private Integer hotelGroupId;

    /**
    *   
     */
    private Integer hotelId;

    /**
    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
     */
    private String lineNo;

    /**
    *   主预定号 规则 YYMMDD00001开始累加，每天前缀都会变化
     */
    private String mainId;

    /**
    *   子订单号规则 YYMMDD00001开始累加，每天前缀都会变化
     */
    private String subId;

    /**
    *   房号
     */
    private String roomCode;

    /**
    *   姓名
     */
    private String personName;

    /**
    *   身份类型 
     */
    private String cardType;

    /**
    *   性别 
     */
    private String sex;

    /**
    *   国家 
     */
    private String nation;

    /**
    *   卡号
     */
    private String cardNo;

    /**
    *   生日 YYYYMMDD
     */
    private String birthday;

    /**
    *   地址
     */
    private String address;

    /**
    *   手机号
     */
    private String mobile;

    /**
    *   邮箱
     */
    private String email;

    /**
    *   会员号
     */
    private String vipNum;

    /**
    *   
     */
    private String remark;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.ROOM_PERSON_ID_
     *
     * @return the value of room_person.ROOM_PERSON_ID_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getRoomPersonId() {
        return roomPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.ROOM_PERSON_ID_
     *
     * @param roomPersonId the value for room_person.ROOM_PERSON_ID_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setRoomPersonId(String roomPersonId) {
        this.roomPersonId = roomPersonId == null ? null : roomPersonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.HOTEL_GROUP_ID_
     *
     * @return the value of room_person.HOTEL_GROUP_ID_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for room_person.HOTEL_GROUP_ID_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.HOTEL_ID_
     *
     * @return the value of room_person.HOTEL_ID_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.HOTEL_ID_
     *
     * @param hotelId the value for room_person.HOTEL_ID_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.LINE_NO_
     *
     * @return the value of room_person.LINE_NO_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.LINE_NO_
     *
     * @param lineNo the value for room_person.LINE_NO_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setLineNo(String lineNo) {
        this.lineNo = lineNo == null ? null : lineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.MAIN_ID_
     *
     * @return the value of room_person.MAIN_ID_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getMainId() {
        return mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.MAIN_ID_
     *
     * @param mainId the value for room_person.MAIN_ID_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setMainId(String mainId) {
        this.mainId = mainId == null ? null : mainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.SUB_ID_
     *
     * @return the value of room_person.SUB_ID_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getSubId() {
        return subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.SUB_ID_
     *
     * @param subId the value for room_person.SUB_ID_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setSubId(String subId) {
        this.subId = subId == null ? null : subId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.ROOM_CODE_
     *
     * @return the value of room_person.ROOM_CODE_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getRoomCode() {
        return roomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.ROOM_CODE_
     *
     * @param roomCode the value for room_person.ROOM_CODE_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setRoomCode(String roomCode) {
        this.roomCode = roomCode == null ? null : roomCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.PERSON_NAME_
     *
     * @return the value of room_person.PERSON_NAME_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.PERSON_NAME_
     *
     * @param personName the value for room_person.PERSON_NAME_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.CARD_TYPE_
     *
     * @return the value of room_person.CARD_TYPE_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.CARD_TYPE_
     *
     * @param cardType the value for room_person.CARD_TYPE_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.SEX_
     *
     * @return the value of room_person.SEX_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.SEX_
     *
     * @param sex the value for room_person.SEX_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.NATION_
     *
     * @return the value of room_person.NATION_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.NATION_
     *
     * @param nation the value for room_person.NATION_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.CARD_NO_
     *
     * @return the value of room_person.CARD_NO_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.CARD_NO_
     *
     * @param cardNo the value for room_person.CARD_NO_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.BIRTHDAY_
     *
     * @return the value of room_person.BIRTHDAY_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.BIRTHDAY_
     *
     * @param birthday the value for room_person.BIRTHDAY_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.ADDRESS_
     *
     * @return the value of room_person.ADDRESS_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.ADDRESS_
     *
     * @param address the value for room_person.ADDRESS_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.MOBILE_
     *
     * @return the value of room_person.MOBILE_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.MOBILE_
     *
     * @param mobile the value for room_person.MOBILE_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.EMAIL_
     *
     * @return the value of room_person.EMAIL_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.EMAIL_
     *
     * @param email the value for room_person.EMAIL_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.VIP_NUM_
     *
     * @return the value of room_person.VIP_NUM_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getVipNum() {
        return vipNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.VIP_NUM_
     *
     * @param vipNum the value for room_person.VIP_NUM_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setVipNum(String vipNum) {
        this.vipNum = vipNum == null ? null : vipNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.REMARK
     *
     * @return the value of room_person.REMARK
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.REMARK
     *
     * @param remark the value for room_person.REMARK
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.CREATE_EMP_
     *
     * @return the value of room_person.CREATE_EMP_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.CREATE_EMP_
     *
     * @param createEmp the value for room_person.CREATE_EMP_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.CREATE_DATE_
     *
     * @return the value of room_person.CREATE_DATE_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.CREATE_DATE_
     *
     * @param createDate the value for room_person.CREATE_DATE_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.UPDATE_DATE_
     *
     * @return the value of room_person.UPDATE_DATE_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.UPDATE_DATE_
     *
     * @param updateDate the value for room_person.UPDATE_DATE_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.UPDATE_EMP_
     *
     * @return the value of room_person.UPDATE_EMP_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.UPDATE_EMP_
     *
     * @param updateEmp the value for room_person.UPDATE_EMP_
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_person.VERSION
     *
     * @return the value of room_person.VERSION
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_person.VERSION
     *
     * @param version the value for room_person.VERSION
     *
     * @mbggenerated Tue Jun 12 10:32:26 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}