package com.whxx.hms.model;

import java.math.BigDecimal;
import java.util.Date;

public class RoomStatus {
    /**
    *   主键
     */
    private String roomStatusId;

    /**
    *   
     */
    private Integer hotelGroupId;

    /**
    *   
     */
    private Integer hotelId;

    /**
    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
     */
    private String lineNo;

    /**
    *   房间号
     */
    private String roomCode;

    /**
    *   扩展房态:  通过系统配置 SYSTEM.EXT_STATUS配置项获取信息。逗号分隔多个状态
     */
    private String extStatus;

    /**
    *   
     */
    private String floorCode;

    /**
    *   
     */
    private String floorName;

    /**
    *   
     */
    private String buildingCode;

    /**
    *   建筑名称
     */
    private String buildingName;

    /**
    *   入住类型:  F=全天房  H=钟点房(钟点房只能直接入住)  L=长包房
     */
    private String inType;

    /**
    *   是否可用于钟点房 Y 是，N否
     */
    private String hourFlag;

    /**
    *   房间状态 是否干净 Y N 仅限当天修改状态
     */
    private String cleanStatus;

    /**
    *   是否住人 Y N 仅限当天修改状态
     */
    private String inFlag;

    /**
    *   是否锁定 Y N 仅限当天修改状态
     */
    private String lockFlag;

    /**
    *   是否将到 Y N 今天开始六个月内可以设定状态
     */
    private String arriveFlag;

    /**
    *   是否将离 Y N 今天开始六个月内可以设定状态
     */
    private String leaveFlag;

    /**
    *   是否维修 Y N
     */
    private String repairFlag;

    /**
    *   房间日期，房间状态所属日期 YYMMDD
     */
    private String roomDateStr;

    /**
    *   子预订单信息，为空表示空房
     */
    private String subId;

    /**
    *   设定的房间价格
     */
    private BigDecimal roomPrice;

    /**
    *   实际的房间价格
     */
    private BigDecimal realPrice;
    
    /**
     *   优惠理由
      */
    private String benefitReason;

    /**
    *   房型码 系统配置 ROOM_TYPE_CODE
     */
    private String roomTypeCode;

    /**
    *   
     */
    private String remark;

    /**
    *   钟点房开始时间
     */
    private Date clockStart;

    /**
    *   钟点房结束时间
     */
    private Date clockEnd;

    /**
    *   锁定开始时间
     */
    private Date lockStart;

    /**
    *   锁定结束时间
     */
    private Date lockEnd;

    /**
    *   锁定原因,通用代码档 LOCK_REPAIR
     */
    private String lockReason;

    /**
    *   维修原因.通用代码档 LOCK_REPAIR
     */
    private String repairSeason;

    /**
    *   房价码
     */
    private String priceCode;

    /**
    *   房价码名称
     */
    private String priceName;

    /**
    *   房间过程。  0 无状态，1报房，2包房完成，3查房 4查毕 
     */
    private String roomProcess;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;
    

    public String getBenefitReason() {
		return benefitReason;
	}

	public void setBenefitReason(String benefitReason) {
		this.benefitReason = benefitReason;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.ROOM_STATUS_ID_
     *
     * @return the value of room_status.ROOM_STATUS_ID_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getRoomStatusId() {
        return roomStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.ROOM_STATUS_ID_
     *
     * @param roomStatusId the value for room_status.ROOM_STATUS_ID_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setRoomStatusId(String roomStatusId) {
        this.roomStatusId = roomStatusId == null ? null : roomStatusId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.HOTEL_GROUP_ID_
     *
     * @return the value of room_status.HOTEL_GROUP_ID_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for room_status.HOTEL_GROUP_ID_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.HOTEL_ID_
     *
     * @return the value of room_status.HOTEL_ID_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.HOTEL_ID_
     *
     * @param hotelId the value for room_status.HOTEL_ID_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.LINE_NO_
     *
     * @return the value of room_status.LINE_NO_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.LINE_NO_
     *
     * @param lineNo the value for room_status.LINE_NO_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setLineNo(String lineNo) {
        this.lineNo = lineNo == null ? null : lineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.ROOM_CODE_
     *
     * @return the value of room_status.ROOM_CODE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getRoomCode() {
        return roomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.ROOM_CODE_
     *
     * @param roomCode the value for room_status.ROOM_CODE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setRoomCode(String roomCode) {
        this.roomCode = roomCode == null ? null : roomCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.EXT_STATUS_
     *
     * @return the value of room_status.EXT_STATUS_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getExtStatus() {
        return extStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.EXT_STATUS_
     *
     * @param extStatus the value for room_status.EXT_STATUS_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setExtStatus(String extStatus) {
        this.extStatus = extStatus == null ? null : extStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.FLOOR_CODE_
     *
     * @return the value of room_status.FLOOR_CODE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getFloorCode() {
        return floorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.FLOOR_CODE_
     *
     * @param floorCode the value for room_status.FLOOR_CODE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setFloorCode(String floorCode) {
        this.floorCode = floorCode == null ? null : floorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.FLOOR_NAME_
     *
     * @return the value of room_status.FLOOR_NAME_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getFloorName() {
        return floorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.FLOOR_NAME_
     *
     * @param floorName the value for room_status.FLOOR_NAME_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setFloorName(String floorName) {
        this.floorName = floorName == null ? null : floorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.BUILDING_CODE_
     *
     * @return the value of room_status.BUILDING_CODE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getBuildingCode() {
        return buildingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.BUILDING_CODE_
     *
     * @param buildingCode the value for room_status.BUILDING_CODE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setBuildingCode(String buildingCode) {
        this.buildingCode = buildingCode == null ? null : buildingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.BUILDING_NAME_
     *
     * @return the value of room_status.BUILDING_NAME_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.BUILDING_NAME_
     *
     * @param buildingName the value for room_status.BUILDING_NAME_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName == null ? null : buildingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.IN_TYPE_
     *
     * @return the value of room_status.IN_TYPE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getInType() {
        return inType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.IN_TYPE_
     *
     * @param inType the value for room_status.IN_TYPE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setInType(String inType) {
        this.inType = inType == null ? null : inType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.HOUR_FLAG_
     *
     * @return the value of room_status.HOUR_FLAG_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getHourFlag() {
        return hourFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.HOUR_FLAG_
     *
     * @param hourFlag the value for room_status.HOUR_FLAG_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setHourFlag(String hourFlag) {
        this.hourFlag = hourFlag == null ? null : hourFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.CLEAN_STATUS_
     *
     * @return the value of room_status.CLEAN_STATUS_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getCleanStatus() {
        return cleanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.CLEAN_STATUS_
     *
     * @param cleanStatus the value for room_status.CLEAN_STATUS_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setCleanStatus(String cleanStatus) {
        this.cleanStatus = cleanStatus == null ? null : cleanStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.IN_FLAG_
     *
     * @return the value of room_status.IN_FLAG_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getInFlag() {
        return inFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.IN_FLAG_
     *
     * @param inFlag the value for room_status.IN_FLAG_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setInFlag(String inFlag) {
        this.inFlag = inFlag == null ? null : inFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.LOCK_FLAG_
     *
     * @return the value of room_status.LOCK_FLAG_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getLockFlag() {
        return lockFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.LOCK_FLAG_
     *
     * @param lockFlag the value for room_status.LOCK_FLAG_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setLockFlag(String lockFlag) {
        this.lockFlag = lockFlag == null ? null : lockFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.ARRIVE_FLAG_
     *
     * @return the value of room_status.ARRIVE_FLAG_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getArriveFlag() {
        return arriveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.ARRIVE_FLAG_
     *
     * @param arriveFlag the value for room_status.ARRIVE_FLAG_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setArriveFlag(String arriveFlag) {
        this.arriveFlag = arriveFlag == null ? null : arriveFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.LEAVE_FLAG_
     *
     * @return the value of room_status.LEAVE_FLAG_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getLeaveFlag() {
        return leaveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.LEAVE_FLAG_
     *
     * @param leaveFlag the value for room_status.LEAVE_FLAG_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setLeaveFlag(String leaveFlag) {
        this.leaveFlag = leaveFlag == null ? null : leaveFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.REPAIR_FLAG_
     *
     * @return the value of room_status.REPAIR_FLAG_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getRepairFlag() {
        return repairFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.REPAIR_FLAG_
     *
     * @param repairFlag the value for room_status.REPAIR_FLAG_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setRepairFlag(String repairFlag) {
        this.repairFlag = repairFlag == null ? null : repairFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.ROOM_DATE_STR_
     *
     * @return the value of room_status.ROOM_DATE_STR_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getRoomDateStr() {
        return roomDateStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.ROOM_DATE_STR_
     *
     * @param roomDateStr the value for room_status.ROOM_DATE_STR_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setRoomDateStr(String roomDateStr) {
        this.roomDateStr = roomDateStr == null ? null : roomDateStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.SUB_ID_
     *
     * @return the value of room_status.SUB_ID_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getSubId() {
        return subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.SUB_ID_
     *
     * @param subId the value for room_status.SUB_ID_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setSubId(String subId) {
        this.subId = subId == null ? null : subId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.ROOM_PRICE_
     *
     * @return the value of room_status.ROOM_PRICE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public BigDecimal getRoomPrice() {
        return roomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.ROOM_PRICE_
     *
     * @param roomPrice the value for room_status.ROOM_PRICE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setRoomPrice(BigDecimal roomPrice) {
        this.roomPrice = roomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.REAL_PRICE_
     *
     * @return the value of room_status.REAL_PRICE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public BigDecimal getRealPrice() {
        return realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.REAL_PRICE_
     *
     * @param realPrice the value for room_status.REAL_PRICE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setRealPrice(BigDecimal realPrice) {
        this.realPrice = realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.ROOM_TYPE_CODE_
     *
     * @return the value of room_status.ROOM_TYPE_CODE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getRoomTypeCode() {
        return roomTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.ROOM_TYPE_CODE_
     *
     * @param roomTypeCode the value for room_status.ROOM_TYPE_CODE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setRoomTypeCode(String roomTypeCode) {
        this.roomTypeCode = roomTypeCode == null ? null : roomTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.REMARK
     *
     * @return the value of room_status.REMARK
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.REMARK
     *
     * @param remark the value for room_status.REMARK
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.CLOCK_START_
     *
     * @return the value of room_status.CLOCK_START_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public Date getClockStart() {
        return clockStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.CLOCK_START_
     *
     * @param clockStart the value for room_status.CLOCK_START_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setClockStart(Date clockStart) {
        this.clockStart = clockStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.CLOCK_END_
     *
     * @return the value of room_status.CLOCK_END_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public Date getClockEnd() {
        return clockEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.CLOCK_END_
     *
     * @param clockEnd the value for room_status.CLOCK_END_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setClockEnd(Date clockEnd) {
        this.clockEnd = clockEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.LOCK_START_
     *
     * @return the value of room_status.LOCK_START_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public Date getLockStart() {
        return lockStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.LOCK_START_
     *
     * @param lockStart the value for room_status.LOCK_START_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setLockStart(Date lockStart) {
        this.lockStart = lockStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.LOCK_END_
     *
     * @return the value of room_status.LOCK_END_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public Date getLockEnd() {
        return lockEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.LOCK_END_
     *
     * @param lockEnd the value for room_status.LOCK_END_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setLockEnd(Date lockEnd) {
        this.lockEnd = lockEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.LOCK_REASON_
     *
     * @return the value of room_status.LOCK_REASON_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getLockReason() {
        return lockReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.LOCK_REASON_
     *
     * @param lockReason the value for room_status.LOCK_REASON_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setLockReason(String lockReason) {
        this.lockReason = lockReason == null ? null : lockReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.REPAIR_SEASON_
     *
     * @return the value of room_status.REPAIR_SEASON_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getRepairSeason() {
        return repairSeason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.REPAIR_SEASON_
     *
     * @param repairSeason the value for room_status.REPAIR_SEASON_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setRepairSeason(String repairSeason) {
        this.repairSeason = repairSeason == null ? null : repairSeason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.PRICE_CODE_
     *
     * @return the value of room_status.PRICE_CODE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getPriceCode() {
        return priceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.PRICE_CODE_
     *
     * @param priceCode the value for room_status.PRICE_CODE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setPriceCode(String priceCode) {
        this.priceCode = priceCode == null ? null : priceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.PRICE_NAME_
     *
     * @return the value of room_status.PRICE_NAME_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getPriceName() {
        return priceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.PRICE_NAME_
     *
     * @param priceName the value for room_status.PRICE_NAME_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setPriceName(String priceName) {
        this.priceName = priceName == null ? null : priceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.ROOM_PROCESS_
     *
     * @return the value of room_status.ROOM_PROCESS_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getRoomProcess() {
        return roomProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.ROOM_PROCESS_
     *
     * @param roomProcess the value for room_status.ROOM_PROCESS_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setRoomProcess(String roomProcess) {
        this.roomProcess = roomProcess == null ? null : roomProcess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.CREATE_EMP_
     *
     * @return the value of room_status.CREATE_EMP_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.CREATE_EMP_
     *
     * @param createEmp the value for room_status.CREATE_EMP_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.CREATE_DATE_
     *
     * @return the value of room_status.CREATE_DATE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.CREATE_DATE_
     *
     * @param createDate the value for room_status.CREATE_DATE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.UPDATE_DATE_
     *
     * @return the value of room_status.UPDATE_DATE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.UPDATE_DATE_
     *
     * @param updateDate the value for room_status.UPDATE_DATE_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.UPDATE_EMP_
     *
     * @return the value of room_status.UPDATE_EMP_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.UPDATE_EMP_
     *
     * @param updateEmp the value for room_status.UPDATE_EMP_
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_status.VERSION
     *
     * @return the value of room_status.VERSION
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_status.VERSION
     *
     * @param version the value for room_status.VERSION
     *
     * @mbggenerated Mon Jun 11 10:32:36 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}