package com.whxx.hms.model;

import java.util.Date;

public class RsvMan {
    /**
    *   
     */
    private String rsvManId;

    /**
    *   
     */
    private Integer hotelGroupId;

    /**
    *   
     */
    private Integer hotelId;

    /**
    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
     */
    private String lineNo;

    /**
    *   协议单位类型 通用代码档
     */
    private String memberType;

    /**
    *   协议单位代码 
     */
    private String memberNo;

    /**
    *   协议单位名称
     */
    private Integer rsvCompany;

    /**
    *   团队领队
     */
    private String groupManager;

    /**
    *   
     */
    private String address;

    /**
    *   联系人
     */
    private String contactPerson;

    /**
    *   手机号
     */
    private String mobile;

    /**
    *   银行号
     */
    private String bankNo;

    /**
    *   销售人员 名称
     */
    private String salesman;

    /**
    *   销售人员主键
     */
    private String salesmanId;

    /**
    *   第二名称，汉字转拼音。如果是英文，不需要转换
     */
    private String nameOther;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.RSV_MAN_ID_
     *
     * @return the value of rsv_man.RSV_MAN_ID_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public String getRsvManId() {
        return rsvManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.RSV_MAN_ID_
     *
     * @param rsvManId the value for rsv_man.RSV_MAN_ID_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setRsvManId(String rsvManId) {
        this.rsvManId = rsvManId == null ? null : rsvManId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.HOTEL_GROUP_ID_
     *
     * @return the value of rsv_man.HOTEL_GROUP_ID_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for rsv_man.HOTEL_GROUP_ID_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.HOTEL_ID_
     *
     * @return the value of rsv_man.HOTEL_ID_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.HOTEL_ID_
     *
     * @param hotelId the value for rsv_man.HOTEL_ID_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.LINE_NO_
     *
     * @return the value of rsv_man.LINE_NO_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public String getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.LINE_NO_
     *
     * @param lineNo the value for rsv_man.LINE_NO_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setLineNo(String lineNo) {
        this.lineNo = lineNo == null ? null : lineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.MEMBER_TYPE_
     *
     * @return the value of rsv_man.MEMBER_TYPE_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public String getMemberType() {
        return memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.MEMBER_TYPE_
     *
     * @param memberType the value for rsv_man.MEMBER_TYPE_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setMemberType(String memberType) {
        this.memberType = memberType == null ? null : memberType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.MEMBER_NO_
     *
     * @return the value of rsv_man.MEMBER_NO_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.MEMBER_NO_
     *
     * @param memberNo the value for rsv_man.MEMBER_NO_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo == null ? null : memberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.RSV_COMPANY_
     *
     * @return the value of rsv_man.RSV_COMPANY_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public Integer getRsvCompany() {
        return rsvCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.RSV_COMPANY_
     *
     * @param rsvCompany the value for rsv_man.RSV_COMPANY_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setRsvCompany(Integer rsvCompany) {
        this.rsvCompany = rsvCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.GROUP_MANAGER_
     *
     * @return the value of rsv_man.GROUP_MANAGER_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public String getGroupManager() {
        return groupManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.GROUP_MANAGER_
     *
     * @param groupManager the value for rsv_man.GROUP_MANAGER_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setGroupManager(String groupManager) {
        this.groupManager = groupManager == null ? null : groupManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.ADDRESS_
     *
     * @return the value of rsv_man.ADDRESS_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.ADDRESS_
     *
     * @param address the value for rsv_man.ADDRESS_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.CONTACT_PERSON_
     *
     * @return the value of rsv_man.CONTACT_PERSON_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.CONTACT_PERSON_
     *
     * @param contactPerson the value for rsv_man.CONTACT_PERSON_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.MOBILE_
     *
     * @return the value of rsv_man.MOBILE_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.MOBILE_
     *
     * @param mobile the value for rsv_man.MOBILE_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.BANK_NO_
     *
     * @return the value of rsv_man.BANK_NO_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.BANK_NO_
     *
     * @param bankNo the value for rsv_man.BANK_NO_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.SALESMAN_
     *
     * @return the value of rsv_man.SALESMAN_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public String getSalesman() {
        return salesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.SALESMAN_
     *
     * @param salesman the value for rsv_man.SALESMAN_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setSalesman(String salesman) {
        this.salesman = salesman == null ? null : salesman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.SALESMAN_ID_
     *
     * @return the value of rsv_man.SALESMAN_ID_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public String getSalesmanId() {
        return salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.SALESMAN_ID_
     *
     * @param salesmanId the value for rsv_man.SALESMAN_ID_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setSalesmanId(String salesmanId) {
        this.salesmanId = salesmanId == null ? null : salesmanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.NAME_OTHER_
     *
     * @return the value of rsv_man.NAME_OTHER_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public String getNameOther() {
        return nameOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.NAME_OTHER_
     *
     * @param nameOther the value for rsv_man.NAME_OTHER_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setNameOther(String nameOther) {
        this.nameOther = nameOther == null ? null : nameOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.CREATE_EMP_
     *
     * @return the value of rsv_man.CREATE_EMP_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.CREATE_EMP_
     *
     * @param createEmp the value for rsv_man.CREATE_EMP_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.CREATE_DATE_
     *
     * @return the value of rsv_man.CREATE_DATE_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.CREATE_DATE_
     *
     * @param createDate the value for rsv_man.CREATE_DATE_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.UPDATE_DATE_
     *
     * @return the value of rsv_man.UPDATE_DATE_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.UPDATE_DATE_
     *
     * @param updateDate the value for rsv_man.UPDATE_DATE_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsv_man.UPDATE_EMP_
     *
     * @return the value of rsv_man.UPDATE_EMP_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsv_man.UPDATE_EMP_
     *
     * @param updateEmp the value for rsv_man.UPDATE_EMP_
     *
     * @mbggenerated Sat Jun 09 14:24:52 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

}