package com.whxx.hms.model;

import java.util.Date;

public class SalesMan {
    /**
    *   销售员主键
     */
    private String salesManId;

    /**
    *   
     */
    private Integer hotelGroupId;

    /**
    *   
     */
    private Integer hotelId;

    /**
    *   销售员代码，引用名 SALESMAN
     */
    private String code;

    /**
    *   
     */
    private String name;

    /**
    *   是否停用 Y N
     */
    private String stopped;

    /**
    *   性别 0女1男2其它
     */
    private String sex;

    /**
    *   CODE_BASE.IDCODE.CODE
     */
    private String idType;

    /**
    *   
     */
    private String idNo;

    /**
    *   
     */
    private String address;

    /**
    *   电话
     */
    private String mobile;

    /**
    *   部门
     */
    private String dept;

    /**
    *   销售区域
     */
    private String salesZone;

    /**
    *   
     */
    private String remark;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.SALES_MAN_ID_
     *
     * @return the value of sales_man.SALES_MAN_ID_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public String getSalesManId() {
        return salesManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.SALES_MAN_ID_
     *
     * @param salesManId the value for sales_man.SALES_MAN_ID_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setSalesManId(String salesManId) {
        this.salesManId = salesManId == null ? null : salesManId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.HOTEL_GROUP_ID
     *
     * @return the value of sales_man.HOTEL_GROUP_ID
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.HOTEL_GROUP_ID
     *
     * @param hotelGroupId the value for sales_man.HOTEL_GROUP_ID
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.HOTEL_ID
     *
     * @return the value of sales_man.HOTEL_ID
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.HOTEL_ID
     *
     * @param hotelId the value for sales_man.HOTEL_ID
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.CODE_
     *
     * @return the value of sales_man.CODE_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.CODE_
     *
     * @param code the value for sales_man.CODE_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.NAME_
     *
     * @return the value of sales_man.NAME_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.NAME_
     *
     * @param name the value for sales_man.NAME_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.STOPPED_
     *
     * @return the value of sales_man.STOPPED_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public String getStopped() {
        return stopped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.STOPPED_
     *
     * @param stopped the value for sales_man.STOPPED_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setStopped(String stopped) {
        this.stopped = stopped == null ? null : stopped.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.SEX_
     *
     * @return the value of sales_man.SEX_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.SEX_
     *
     * @param sex the value for sales_man.SEX_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.ID_TYPE_
     *
     * @return the value of sales_man.ID_TYPE_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.ID_TYPE_
     *
     * @param idType the value for sales_man.ID_TYPE_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setIdType(String idType) {
        this.idType = idType == null ? null : idType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.ID_NO_
     *
     * @return the value of sales_man.ID_NO_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.ID_NO_
     *
     * @param idNo the value for sales_man.ID_NO_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.ADDRESS_
     *
     * @return the value of sales_man.ADDRESS_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.ADDRESS_
     *
     * @param address the value for sales_man.ADDRESS_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.MOBILE
     *
     * @return the value of sales_man.MOBILE
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.MOBILE
     *
     * @param mobile the value for sales_man.MOBILE
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.DEPT_
     *
     * @return the value of sales_man.DEPT_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.DEPT_
     *
     * @param dept the value for sales_man.DEPT_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.SALES_ZONE_
     *
     * @return the value of sales_man.SALES_ZONE_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public String getSalesZone() {
        return salesZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.SALES_ZONE_
     *
     * @param salesZone the value for sales_man.SALES_ZONE_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setSalesZone(String salesZone) {
        this.salesZone = salesZone == null ? null : salesZone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.REMARK
     *
     * @return the value of sales_man.REMARK
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.REMARK
     *
     * @param remark the value for sales_man.REMARK
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.CREATE_EMP_
     *
     * @return the value of sales_man.CREATE_EMP_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.CREATE_EMP_
     *
     * @param createEmp the value for sales_man.CREATE_EMP_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.CREATE_DATE_
     *
     * @return the value of sales_man.CREATE_DATE_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.CREATE_DATE_
     *
     * @param createDate the value for sales_man.CREATE_DATE_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.UPDATE_DATE_
     *
     * @return the value of sales_man.UPDATE_DATE_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.UPDATE_DATE_
     *
     * @param updateDate the value for sales_man.UPDATE_DATE_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.UPDATE_EMP_
     *
     * @return the value of sales_man.UPDATE_EMP_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.UPDATE_EMP_
     *
     * @param updateEmp the value for sales_man.UPDATE_EMP_
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_man.VERSION
     *
     * @return the value of sales_man.VERSION
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_man.VERSION
     *
     * @param version the value for sales_man.VERSION
     *
     * @mbggenerated Tue Jun 12 17:36:54 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}