package com.whxx.hms.model;

import java.util.Date;

public class SrcCode {
    /**
    *   
     */
    private String srcCodeId;

    /**
    *   
     */
    private Integer hotelGroupId;

    /**
    *   
     */
    private Integer hotelId;

    /**
    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
     */
    private String lineNo;

    /**
    *   序号
     */
    private Integer seq;

    /**
    *   费用代码
     */
    private String srcCode;

    /**
    *   
     */
    private String zhName;

    /**
    *   
     */
    private String enName;

    /**
    *   来源所属组
     */
    private String srcGroup;

    /**
    *   是否停用 Y N
     */
    private String stopped;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_code.SRC_CODE_ID_
     *
     * @return the value of src_code.SRC_CODE_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getSrcCodeId() {
        return srcCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_code.SRC_CODE_ID_
     *
     * @param srcCodeId the value for src_code.SRC_CODE_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setSrcCodeId(String srcCodeId) {
        this.srcCodeId = srcCodeId == null ? null : srcCodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_code.HOTEL_GROUP_ID_
     *
     * @return the value of src_code.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_code.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for src_code.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_code.HOTEL_ID_
     *
     * @return the value of src_code.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_code.HOTEL_ID_
     *
     * @param hotelId the value for src_code.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_code.LINE_NO_
     *
     * @return the value of src_code.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_code.LINE_NO_
     *
     * @param lineNo the value for src_code.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setLineNo(String lineNo) {
        this.lineNo = lineNo == null ? null : lineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_code.SEQ_
     *
     * @return the value of src_code.SEQ_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_code.SEQ_
     *
     * @param seq the value for src_code.SEQ_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_code.SRC_CODE_
     *
     * @return the value of src_code.SRC_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getSrcCode() {
        return srcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_code.SRC_CODE_
     *
     * @param srcCode the value for src_code.SRC_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setSrcCode(String srcCode) {
        this.srcCode = srcCode == null ? null : srcCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_code.ZH_NAME_
     *
     * @return the value of src_code.ZH_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getZhName() {
        return zhName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_code.ZH_NAME_
     *
     * @param zhName the value for src_code.ZH_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setZhName(String zhName) {
        this.zhName = zhName == null ? null : zhName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_code.EN_NAME_
     *
     * @return the value of src_code.EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_code.EN_NAME_
     *
     * @param enName the value for src_code.EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_code.SRC_GROUP_
     *
     * @return the value of src_code.SRC_GROUP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getSrcGroup() {
        return srcGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_code.SRC_GROUP_
     *
     * @param srcGroup the value for src_code.SRC_GROUP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setSrcGroup(String srcGroup) {
        this.srcGroup = srcGroup == null ? null : srcGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_code.STOPPED_
     *
     * @return the value of src_code.STOPPED_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getStopped() {
        return stopped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_code.STOPPED_
     *
     * @param stopped the value for src_code.STOPPED_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setStopped(String stopped) {
        this.stopped = stopped == null ? null : stopped.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_code.CREATE_EMP_
     *
     * @return the value of src_code.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_code.CREATE_EMP_
     *
     * @param createEmp the value for src_code.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_code.CREATE_DATE_
     *
     * @return the value of src_code.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_code.CREATE_DATE_
     *
     * @param createDate the value for src_code.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_code.UPDATE_DATE_
     *
     * @return the value of src_code.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_code.UPDATE_DATE_
     *
     * @param updateDate the value for src_code.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_code.UPDATE_EMP_
     *
     * @return the value of src_code.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_code.UPDATE_EMP_
     *
     * @param updateEmp the value for src_code.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_code.VERSION
     *
     * @return the value of src_code.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_code.VERSION
     *
     * @param version the value for src_code.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}