package com.whxx.hms.model;

import java.util.Date;

public class TbHotel {
    /**
    *   主键
     */
    private String tbHotelId;

    /**
    *   集团编号
     */
    private Integer hotelGroupId;

    /**
    *   酒店编号
     */
    private Integer hotelId;

    /**
    *   序号 17位 yyyyMMddHHmmssfff 年年年年月月日日时时分分秒秒3位毫秒
     */
    private String lineNo;

    /**
    *   酒店名称
     */
    private String hotelName;

    /**
    *   酒店代码
     */
    private String hotelCode;

    /**
    *   酒店地址
     */
    private String hotelAddress;

    /**
    *   酒店电话
     */
    private String hotelPhone;

    /**
    *   酒店图
     */
    private String img;

    /**
    *   酒店星级
     */
    private Integer stars;

    /**
    *   地址
     */
    private String coordinate;

    /**
    *   地图链接地址
     */
    private String mapUrl;

    /**
    *   备注
     */
    private String remark;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.TB_HOTEL_ID_
     *
     * @return the value of tb_hotel.TB_HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getTbHotelId() {
        return tbHotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.TB_HOTEL_ID_
     *
     * @param tbHotelId the value for tb_hotel.TB_HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setTbHotelId(String tbHotelId) {
        this.tbHotelId = tbHotelId == null ? null : tbHotelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.HOTEL_GROUP_ID_
     *
     * @return the value of tb_hotel.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for tb_hotel.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.HOTEL_ID_
     *
     * @return the value of tb_hotel.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.HOTEL_ID_
     *
     * @param hotelId the value for tb_hotel.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.LINE_NO_
     *
     * @return the value of tb_hotel.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.LINE_NO_
     *
     * @param lineNo the value for tb_hotel.LINE_NO_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setLineNo(String lineNo) {
        this.lineNo = lineNo == null ? null : lineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.HOTEL_NAME_
     *
     * @return the value of tb_hotel.HOTEL_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.HOTEL_NAME_
     *
     * @param hotelName the value for tb_hotel.HOTEL_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName == null ? null : hotelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.HOTEL_CODE_
     *
     * @return the value of tb_hotel.HOTEL_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getHotelCode() {
        return hotelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.HOTEL_CODE_
     *
     * @param hotelCode the value for tb_hotel.HOTEL_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelCode(String hotelCode) {
        this.hotelCode = hotelCode == null ? null : hotelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.HOTEL_ADDRESS_
     *
     * @return the value of tb_hotel.HOTEL_ADDRESS_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getHotelAddress() {
        return hotelAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.HOTEL_ADDRESS_
     *
     * @param hotelAddress the value for tb_hotel.HOTEL_ADDRESS_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelAddress(String hotelAddress) {
        this.hotelAddress = hotelAddress == null ? null : hotelAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.HOTEL_PHONE_
     *
     * @return the value of tb_hotel.HOTEL_PHONE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getHotelPhone() {
        return hotelPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.HOTEL_PHONE_
     *
     * @param hotelPhone the value for tb_hotel.HOTEL_PHONE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelPhone(String hotelPhone) {
        this.hotelPhone = hotelPhone == null ? null : hotelPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.IMG_
     *
     * @return the value of tb_hotel.IMG_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.IMG_
     *
     * @param img the value for tb_hotel.IMG_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.STARS_
     *
     * @return the value of tb_hotel.STARS_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.STARS_
     *
     * @param stars the value for tb_hotel.STARS_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setStars(Integer stars) {
        this.stars = stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.COORDINATE_
     *
     * @return the value of tb_hotel.COORDINATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getCoordinate() {
        return coordinate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.COORDINATE_
     *
     * @param coordinate the value for tb_hotel.COORDINATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCoordinate(String coordinate) {
        this.coordinate = coordinate == null ? null : coordinate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.MAP_URL_
     *
     * @return the value of tb_hotel.MAP_URL_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getMapUrl() {
        return mapUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.MAP_URL_
     *
     * @param mapUrl the value for tb_hotel.MAP_URL_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setMapUrl(String mapUrl) {
        this.mapUrl = mapUrl == null ? null : mapUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.REMARK_
     *
     * @return the value of tb_hotel.REMARK_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.REMARK_
     *
     * @param remark the value for tb_hotel.REMARK_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.CREATE_EMP_
     *
     * @return the value of tb_hotel.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.CREATE_EMP_
     *
     * @param createEmp the value for tb_hotel.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.CREATE_DATE_
     *
     * @return the value of tb_hotel.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.CREATE_DATE_
     *
     * @param createDate the value for tb_hotel.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.UPDATE_DATE_
     *
     * @return the value of tb_hotel.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.UPDATE_DATE_
     *
     * @param updateDate the value for tb_hotel.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.UPDATE_EMP_
     *
     * @return the value of tb_hotel.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.UPDATE_EMP_
     *
     * @param updateEmp the value for tb_hotel.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hotel.VERSION
     *
     * @return the value of tb_hotel.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hotel.VERSION
     *
     * @param version the value for tb_hotel.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}