package com.whxx.hms.model;

import java.util.Date;

public class Tbpp01a {
    /**
    *   主键
     */
    private String tbpp01aId;

    /**
    *   
     */
    private Long hotelGroupId;

    /**
    *   
     */
    private Long hotelId;

    /**
    *   逻辑外键
     */
    private String tbpp01Id;

    /**
    *   配置项目代码
     */
    private String configCode;

    /**
    *   中文名
     */
    private String zhName;

    /**
    *   英文名
     */
    private String enName;

    /**
    *   系统码标示：Y  是，N 否
     */
    private String sysFlag;

    /**
    *   是否停用
     */
    private String stopped;

    /**
    *   顺序号
     */
    private String seq;

    /**
    *   描述
     */
    private String desc;

    /**
    *   描述1
     */
    private String desc1;

    /**
    *   描述2
     */
    private String desc2;

    /**
    *   描述3
     */
    private String desc3;

    /**
    *   描述4
     */
    private String desc4;

    /**
    *   描述5
     */
    private String desc5;

    /**
    *   描述6
     */
    private String desc6;

    /**
    *   描述7
     */
    private String desc7;

    /**
    *   描述8
     */
    private String desc8;

    /**
    *   描述9
     */
    private String desc9;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.TBPP01A_ID_
     *
     * @return the value of tbpp01a.TBPP01A_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getTbpp01aId() {
        return tbpp01aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.TBPP01A_ID_
     *
     * @param tbpp01aId the value for tbpp01a.TBPP01A_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setTbpp01aId(String tbpp01aId) {
        this.tbpp01aId = tbpp01aId == null ? null : tbpp01aId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.HOTEL_GROUP_ID_
     *
     * @return the value of tbpp01a.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Long getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for tbpp01a.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelGroupId(Long hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.HOTEL_ID_
     *
     * @return the value of tbpp01a.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Long getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.HOTEL_ID_
     *
     * @param hotelId the value for tbpp01a.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelId(Long hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.TBPP01_ID_
     *
     * @return the value of tbpp01a.TBPP01_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getTbpp01Id() {
        return tbpp01Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.TBPP01_ID_
     *
     * @param tbpp01Id the value for tbpp01a.TBPP01_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setTbpp01Id(String tbpp01Id) {
        this.tbpp01Id = tbpp01Id == null ? null : tbpp01Id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.CONFIG_CODE_
     *
     * @return the value of tbpp01a.CONFIG_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getConfigCode() {
        return configCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.CONFIG_CODE_
     *
     * @param configCode the value for tbpp01a.CONFIG_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setConfigCode(String configCode) {
        this.configCode = configCode == null ? null : configCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.ZH_NAME_
     *
     * @return the value of tbpp01a.ZH_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getZhName() {
        return zhName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.ZH_NAME_
     *
     * @param zhName the value for tbpp01a.ZH_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setZhName(String zhName) {
        this.zhName = zhName == null ? null : zhName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.EN_NAME_
     *
     * @return the value of tbpp01a.EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.EN_NAME_
     *
     * @param enName the value for tbpp01a.EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.SYS_FLAG_
     *
     * @return the value of tbpp01a.SYS_FLAG_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getSysFlag() {
        return sysFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.SYS_FLAG_
     *
     * @param sysFlag the value for tbpp01a.SYS_FLAG_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setSysFlag(String sysFlag) {
        this.sysFlag = sysFlag == null ? null : sysFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.STOPPED_
     *
     * @return the value of tbpp01a.STOPPED_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getStopped() {
        return stopped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.STOPPED_
     *
     * @param stopped the value for tbpp01a.STOPPED_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setStopped(String stopped) {
        this.stopped = stopped == null ? null : stopped.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.SEQ_
     *
     * @return the value of tbpp01a.SEQ_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.SEQ_
     *
     * @param seq the value for tbpp01a.SEQ_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setSeq(String seq) {
        this.seq = seq == null ? null : seq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.DESC_
     *
     * @return the value of tbpp01a.DESC_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.DESC_
     *
     * @param desc the value for tbpp01a.DESC_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.DESC1_
     *
     * @return the value of tbpp01a.DESC1_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getDesc1() {
        return desc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.DESC1_
     *
     * @param desc1 the value for tbpp01a.DESC1_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setDesc1(String desc1) {
        this.desc1 = desc1 == null ? null : desc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.DESC2_
     *
     * @return the value of tbpp01a.DESC2_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getDesc2() {
        return desc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.DESC2_
     *
     * @param desc2 the value for tbpp01a.DESC2_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setDesc2(String desc2) {
        this.desc2 = desc2 == null ? null : desc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.DESC3_
     *
     * @return the value of tbpp01a.DESC3_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getDesc3() {
        return desc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.DESC3_
     *
     * @param desc3 the value for tbpp01a.DESC3_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setDesc3(String desc3) {
        this.desc3 = desc3 == null ? null : desc3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.DESC4_
     *
     * @return the value of tbpp01a.DESC4_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getDesc4() {
        return desc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.DESC4_
     *
     * @param desc4 the value for tbpp01a.DESC4_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setDesc4(String desc4) {
        this.desc4 = desc4 == null ? null : desc4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.DESC5_
     *
     * @return the value of tbpp01a.DESC5_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getDesc5() {
        return desc5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.DESC5_
     *
     * @param desc5 the value for tbpp01a.DESC5_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setDesc5(String desc5) {
        this.desc5 = desc5 == null ? null : desc5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.DESC6_
     *
     * @return the value of tbpp01a.DESC6_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getDesc6() {
        return desc6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.DESC6_
     *
     * @param desc6 the value for tbpp01a.DESC6_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setDesc6(String desc6) {
        this.desc6 = desc6 == null ? null : desc6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.DESC7_
     *
     * @return the value of tbpp01a.DESC7_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getDesc7() {
        return desc7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.DESC7_
     *
     * @param desc7 the value for tbpp01a.DESC7_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setDesc7(String desc7) {
        this.desc7 = desc7 == null ? null : desc7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.DESC8_
     *
     * @return the value of tbpp01a.DESC8_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getDesc8() {
        return desc8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.DESC8_
     *
     * @param desc8 the value for tbpp01a.DESC8_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setDesc8(String desc8) {
        this.desc8 = desc8 == null ? null : desc8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.DESC9_
     *
     * @return the value of tbpp01a.DESC9_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getDesc9() {
        return desc9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.DESC9_
     *
     * @param desc9 the value for tbpp01a.DESC9_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setDesc9(String desc9) {
        this.desc9 = desc9 == null ? null : desc9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.CREATE_EMP_
     *
     * @return the value of tbpp01a.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.CREATE_EMP_
     *
     * @param createEmp the value for tbpp01a.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.CREATE_DATE_
     *
     * @return the value of tbpp01a.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.CREATE_DATE_
     *
     * @param createDate the value for tbpp01a.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.UPDATE_DATE_
     *
     * @return the value of tbpp01a.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.UPDATE_DATE_
     *
     * @param updateDate the value for tbpp01a.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.UPDATE_EMP_
     *
     * @return the value of tbpp01a.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.UPDATE_EMP_
     *
     * @param updateEmp the value for tbpp01a.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01a.VERSION
     *
     * @return the value of tbpp01a.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01a.VERSION
     *
     * @param version the value for tbpp01a.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}