package com.whxx.hms.model;

import java.util.Date;

public class Tbpp01 {
    /**
    *   主键
     */
    private String tbpp01Id;

    /**
    *   
     */
    private Integer hotelGroupId;

    /**
    *   
     */
    private Integer hotelId;

    /**
    *   配置项目代码
     */
    private String configCode;

    /**
    *   配置项目名称
     */
    private String configName;

    /**
    *   系统码标示：Y  是，N 否
     */
    private String sysFlag;

    /**
    *   代码配置级别：1只有一级，2有两级
     */
    private String level;

    /**
    *   数值
     */
    private String configValue;

    /**
    *   中文名
     */
    private String zhName;

    /**
    *   英文名
     */
    private String enName;

    /**
    *   备注
     */
    private String notice;

    /**
    *   备注1
     */
    private String remark1;

    /**
    *   备注2
     */
    private String remark2;

    /**
    *   备注3
     */
    private String remark3;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.TBPP01_ID_
     *
     * @return the value of tbpp01.TBPP01_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getTbpp01Id() {
        return tbpp01Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.TBPP01_ID_
     *
     * @param tbpp01Id the value for tbpp01.TBPP01_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setTbpp01Id(String tbpp01Id) {
        this.tbpp01Id = tbpp01Id == null ? null : tbpp01Id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.HOTEL_GROUP_ID_
     *
     * @return the value of tbpp01.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelGroupId() {
        return hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.HOTEL_GROUP_ID_
     *
     * @param hotelGroupId the value for tbpp01.HOTEL_GROUP_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelGroupId(Integer hotelGroupId) {
        this.hotelGroupId = hotelGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.HOTEL_ID_
     *
     * @return the value of tbpp01.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.HOTEL_ID_
     *
     * @param hotelId the value for tbpp01.HOTEL_ID_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.CONFIG_CODE_
     *
     * @return the value of tbpp01.CONFIG_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getConfigCode() {
        return configCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.CONFIG_CODE_
     *
     * @param configCode the value for tbpp01.CONFIG_CODE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setConfigCode(String configCode) {
        this.configCode = configCode == null ? null : configCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.CONFIG_NAME_
     *
     * @return the value of tbpp01.CONFIG_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.CONFIG_NAME_
     *
     * @param configName the value for tbpp01.CONFIG_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.SYS_FLAG_
     *
     * @return the value of tbpp01.SYS_FLAG_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getSysFlag() {
        return sysFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.SYS_FLAG_
     *
     * @param sysFlag the value for tbpp01.SYS_FLAG_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setSysFlag(String sysFlag) {
        this.sysFlag = sysFlag == null ? null : sysFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.LEVEL_
     *
     * @return the value of tbpp01.LEVEL_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.LEVEL_
     *
     * @param level the value for tbpp01.LEVEL_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.CONFIG_VALUE_
     *
     * @return the value of tbpp01.CONFIG_VALUE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.CONFIG_VALUE_
     *
     * @param configValue the value for tbpp01.CONFIG_VALUE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.ZH_NAME_
     *
     * @return the value of tbpp01.ZH_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getZhName() {
        return zhName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.ZH_NAME_
     *
     * @param zhName the value for tbpp01.ZH_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setZhName(String zhName) {
        this.zhName = zhName == null ? null : zhName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.EN_NAME_
     *
     * @return the value of tbpp01.EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.EN_NAME_
     *
     * @param enName the value for tbpp01.EN_NAME_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.NOTICE_
     *
     * @return the value of tbpp01.NOTICE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.NOTICE_
     *
     * @param notice the value for tbpp01.NOTICE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setNotice(String notice) {
        this.notice = notice == null ? null : notice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.REMARK1_
     *
     * @return the value of tbpp01.REMARK1_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.REMARK1_
     *
     * @param remark1 the value for tbpp01.REMARK1_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.REMARK2_
     *
     * @return the value of tbpp01.REMARK2_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.REMARK2_
     *
     * @param remark2 the value for tbpp01.REMARK2_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.REMARK3_
     *
     * @return the value of tbpp01.REMARK3_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.REMARK3_
     *
     * @param remark3 the value for tbpp01.REMARK3_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.CREATE_EMP_
     *
     * @return the value of tbpp01.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.CREATE_EMP_
     *
     * @param createEmp the value for tbpp01.CREATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.CREATE_DATE_
     *
     * @return the value of tbpp01.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.CREATE_DATE_
     *
     * @param createDate the value for tbpp01.CREATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.UPDATE_DATE_
     *
     * @return the value of tbpp01.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.UPDATE_DATE_
     *
     * @param updateDate the value for tbpp01.UPDATE_DATE_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.UPDATE_EMP_
     *
     * @return the value of tbpp01.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.UPDATE_EMP_
     *
     * @param updateEmp the value for tbpp01.UPDATE_EMP_
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpp01.VERSION
     *
     * @return the value of tbpp01.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpp01.VERSION
     *
     * @param version the value for tbpp01.VERSION
     *
     * @mbggenerated Thu Jun 07 18:42:36 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}